'use client';
import { useEffect,useRef,useState,type FormEvent } from 'react';
type Draft={contactName:string;contactEmail:string;contactPhone:string;need:string;requestedDate:string;participants:string;budgetMinor:string;budgetBasis:string;website:string};
type Metadata={formId:string;caveName:string;intro:string;challenge:string;minimumDelayMs:number};
type Pending={body:Record<string,unknown>;draft:Draft;meta:Metadata};
type Receipt={received:true;reference:string;caveName:string};
const empty:Draft={contactName:'',contactEmail:'',contactPhone:'',need:'',requestedDate:'',participants:'',budgetMinor:'',budgetBasis:'',website:''};
const messages:Record<string,string>={rate_limited:'Le formulaire a reçu trop de tentatives. Patientez avant de réessayer.',too_fast:'Patientez quelques instants avant l’envoi.',form_unavailable:'Ce formulaire est indisponible. Revenez au site de la cave pour la contacter.',challenge_expired:'Le délai de saisie a expiré. Actualisez le formulaire en conservant vos informations.',invalid_challenge:'Ce formulaire a expiré. Actualisez-le en conservant vos informations.',form_changed:'La cave a modifié le formulaire. Actualisez-le en conservant vos informations.',submission_rejected:'L’envoi a été refusé. Vérifiez vos informations.',origin_forbidden:'Cette page ne peut pas envoyer la demande. Ouvrez le formulaire depuis le site de la cave.'};
export default function PublicForm({id}:{id:string}){
  const key='encave-public:'+id,[draft,setDraft]=useState<Draft>(empty),[meta,setMeta]=useState<Metadata|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[pending,setPending]=useState<Pending|null>(null),[receipt,setReceipt]=useState<Receipt|null>(null),[error,setError]=useState(''),[fields,setFields]=useState<Record<string,string>>({}),[refreshNeeded,setRefreshNeeded]=useState(false),[waitSeconds,setWaitSeconds]=useState<number|null>(null);
  const alert=useRef<HTMLDivElement>(null),heading=useRef<HTMLHeadingElement>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null),generation=useRef(0);
  useEffect(()=>{if(error)alert.current?.focus();},[error]);
  useEffect(()=>{if(receipt)heading.current?.focus();},[receipt]);
  async function load(retained=false){const current=++generation.current;setLoading(true);setReady(false);try{const r=await fetch('/api/public/forms/'+encodeURIComponent(id),{credentials:'omit',cache:'no-store'}),data=await r.json();if(current!==generation.current)return;if(!r.ok){if(!retained)setError(messages[data.error]??'Le formulaire ne peut pas être chargé. Réessayez.');return;}setMeta(data);if(!retained)setError('');setRefreshNeeded(false);if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>setReady(true),data.minimumDelayMs+100);}catch{if(current===generation.current&&!retained)setError('Le formulaire ne peut pas être chargé. Vérifiez votre connexion puis réessayez.');}finally{if(current===generation.current)setLoading(false);}}
  useEffect(()=>{let retained=false;try{const stored=JSON.parse(sessionStorage.getItem(key)??'null');if(stored?.receipt){setReceipt(stored.receipt);setLoading(false);return;}if(stored?.pending){setPending(stored.pending);setDraft(stored.pending.draft);setMeta(stored.pending.meta);setError('La réception de votre demande reste à vérifier. Vos informations sont conservées pour reprendre le même envoi.');retained=true;}}catch{}void load(retained);return()=>{generation.current++;if(timer.current)clearTimeout(timer.current);};},[id]);
  useEffect(()=>{const guard=(event:BeforeUnloadEvent)=>{if(!receipt&&Object.values(draft).some(Boolean)){event.preventDefault();}};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[draft,receipt]);
  const locked=busy||pending!==null;
  const change=(name:keyof Draft,value:string)=>setDraft(d=>({...d,[name]:value}));
  const field=(name:keyof Draft,label:string,type='text',max?:number,help?:string)=><div><label htmlFor={name}>{label}</label><input id={name} type={type} maxLength={max} value={draft[name]} disabled={locked} onChange={e=>change(name,e.target.value)} aria-invalid={Boolean(fields[name])} aria-describedby={[help?'help-'+name:'',fields[name]?'error-'+name:''].filter(Boolean).join(' ')||undefined}/>{help&&<p className="help" id={'help-'+name}>{help}</p>}{fields[name]&&<p className="field-error" id={'error-'+name}>{fields[name]}</p>}</div>;
  async function submit(event:FormEvent){event.preventDefault();if(busy||!meta||(!ready&&!pending))return;setFields({});setError('');setWaitSeconds(null);
    let command=pending;
    if(!command){const invalid:Record<string,string>={};if(draft.budgetMinor&&!/^\d+(?:[.,]\d{1,2})?$/.test(draft.budgetMinor))invalid.budgetMinor='Indiquez un montant CHF positif avec deux décimales maximum.';if(draft.participants&&!/^\d+$/.test(draft.participants))invalid.participants='Indiquez un nombre entier de personnes.';if(Object.keys(invalid).length){setFields(invalid);setError('Vérifiez les informations indiquées.');return;}
      const inquiry={contactName:draft.contactName,contactEmail:draft.contactEmail.trim()||null,contactPhone:draft.contactPhone.trim()||null,need:draft.need,requestedDate:draft.requestedDate||null,participants:draft.participants?Number(draft.participants):null,budgetMinor:draft.budgetMinor?Math.round(Number(draft.budgetMinor.replace(',','.'))*100):null,budgetBasis:draft.budgetBasis||null};command={body:{inquiry,challenge:meta.challenge,requestKey:crypto.randomUUID(),website:draft.website},draft,meta};
      try{sessionStorage.setItem(key,JSON.stringify({pending:command}));}catch{setError('Le navigateur ne peut pas conserver la reprise de cet envoi. Activez son stockage pour ce site puis réessayez.');return;}}
    setBusy(true);setPending(command);
    try{const r=await fetch('/api/public/forms/'+encodeURIComponent(id),{method:'POST',credentials:'omit',headers:{'content-type':'application/json'},body:JSON.stringify(command.body)}),data=await r.json();
      if(r.ok&&data.received===true){setReceipt(data);setPending(null);try{sessionStorage.setItem(key,JSON.stringify({receipt:data}));}catch{}return;}
      const knownAbsent=data.notCreated===true||(!pending&&r.status===400&&data.fields);
      if(knownAbsent){setPending(null);try{sessionStorage.removeItem(key);}catch{}setRefreshNeeded(['challenge_expired','invalid_challenge','form_changed'].includes(data.error));}
      if(data.fields&&!pending)setFields(data.fields);setWaitSeconds(data.retryAfter??null);
      setError((messages[data.error]??(data.fields?'Vérifiez les informations indiquées.':'La réception de votre demande n’est pas confirmée.'))+(knownAbsent?'':' Vos informations restent conservées. Vérifiez la réception avec le même envoi.'));
    }catch{setError('La réception de votre demande n’est pas confirmée. Vos informations restent conservées. Vérifiez la réception avec le même envoi.');}finally{setBusy(false);}
  }
  return <div className="public-page"><header className="public-header"><span className="brand">EnCave <span>Assistant</span></span><span>Demande auprès de la cave</span></header><main id="contenu" className="public-main">
    {receipt?<section className="public-card"><p className="eyebrow">{receipt.caveName}</p><h1 tabIndex={-1} ref={heading}>Demande reçue</h1><p role="status">Votre demande a été enregistrée auprès de {receipt.caveName}.</p><p className="public-reference">Référence : <strong>{receipt.reference}</strong></p><p>La cave dispose du moyen de réponse que vous avez indiqué. Elle examinera votre demande ; aucune réservation n’est encore confirmée.</p><button className="button secondary" onClick={()=>{try{sessionStorage.removeItem(key);}catch{}setReceipt(null);setDraft(empty);setMeta(null);void load();}}>Faire une autre demande</button></section>:<>
    <p className="eyebrow">{meta?.caveName??'Formulaire de la cave'}</p><h1>Demander une visite</h1>{meta&&<p className="public-intro">{meta.intro}</p>}
    {loading&&<p className="loading-state" role="status">Chargement du formulaire…</p>}
    {error&&<div ref={alert} tabIndex={-1} role="alert" className="alert warning"><p>{error}</p>{Object.keys(fields).length>0&&<ul>{Object.entries(fields).filter(([name])=>Object.hasOwn(draft,name)&&name!=='website').map(([name,message])=><li key={name}><a className="error-link" href={'#'+name} onClick={event=>{event.preventDefault();document.getElementById(name)?.focus();}}>{message}</a></li>)}</ul>}{waitSeconds!==null&&<p>Nouvel essai possible après {waitSeconds} seconde{waitSeconds>1?'s':''}.</p>}</div>}
    {!meta&&!loading&&<button className="button secondary" onClick={()=>void load()}>Réessayer de charger</button>}
    {meta&&<form className="public-card" noValidate onSubmit={submit}><h2>Votre demande à {meta.caveName}</h2><p>Votre nom, votre besoin et au moins un moyen de réponse sont nécessaires. Aucun compte n’est demandé.</p><div className="form-grid">
    {field('contactName','Votre nom','text',160)}{field('contactEmail','Adresse e-mail','email',254,'Un e-mail ou un téléphone suffit pour que la cave puisse vous répondre.')}{field('contactPhone','Téléphone','tel',40)}
    </div><label htmlFor="need">Votre besoin</label><textarea id="need" maxLength={4000} value={draft.need} disabled={locked} onChange={e=>change('need',e.target.value)} aria-invalid={Boolean(fields.need)} aria-describedby={fields.need?'error-need':undefined}/>{fields.need&&<p className="field-error" id="error-need">{fields.need}</p>}
    <h3>Si vous le savez déjà</h3><div className="form-grid">{field('requestedDate','Date souhaitée (facultatif)','date')}{field('participants','Nombre de personnes (facultatif)','text',6)}{field('budgetMinor','Budget en CHF (facultatif)','text',15)}<div><label htmlFor="budgetBasis">Ce budget concerne (facultatif)</label><select id="budgetBasis" value={draft.budgetBasis} disabled={locked} onChange={e=>change('budgetBasis',e.target.value)} aria-invalid={Boolean(fields.budgetBasis)} aria-describedby={fields.budgetBasis?'error-budgetBasis':undefined}><option value="">À préciser</option><option value="group">Le groupe</option><option value="person">Chaque personne</option></select>{fields.budgetBasis&&<p className="field-error" id="error-budgetBasis">{fields.budgetBasis}</p>}</div></div>
    <div className="public-honeypot" aria-hidden="true"><label htmlFor="website">Site web</label><input id="website" tabIndex={-1} autoComplete="off" value={draft.website} onChange={e=>change('website',e.target.value)}/></div>
    <p className="help">Les informations saisies sont transmises à cette cave pour traiter votre demande.</p>{busy&&<p role="status">Envoi en cours…</p>}
    <div className="form-actions">{refreshNeeded?<button className="button secondary" type="button" disabled={loading} onClick={()=>void load()}>Actualiser en conservant ma saisie</button>:<button className="button primary" type="submit" disabled={busy||(!pending&&(!ready||loading))}>{pending?'Vérifier la réception':'Envoyer ma demande'}</button>}</div>
    </form>}</>}
    <p className="help public-footer">EnCave Assistant · Service de demandes de visites et dégustations</p>
  </main></div>;
}
