import test from 'node:test';
import assert from 'node:assert/strict';
import { ConnectionStore } from '../../../apps/api/src/connection-store.ts';
import { connectionHarness,HttpBrowser,connectAccount,listConnections,selectConnection,operateConnection,beginConnection,caveA,caveB } from '../helpers/connection-harness.mjs';
async function active(f,b,account){let row=await selectConnection(b,await connectAccount(f,b,account));assert.equal((await operateConnection(b,row,'activate')).status,200);return(await listConnections(b)).body.items.find(x=>x.id===row.id);}
const job=row=>({caveId:row.identity.accountId.startsWith('a')?caveA:caveB,connectionId:row.id,authorizationVersion:row.authorizationVersion});
test('EA-13 AC-01/05: revocation stops in-flight discovery and stale jobs without affecting cave B',async()=>{
 const f=await connectionHarness();try{const a=new HttpBrowser(f.appOrigin),b=new HttpBrowser(f.appOrigin);await a.login('alice');await b.login('emile');let ra=await active(f,a,'a'),rb=await active(f,b,'b');assert.equal((await f.connectionStore.runDiscoveryJob(job(rb))).synthetic,true);
 let reached,release;const entered=new Promise(r=>reached=r),held=new Promise(r=>release=r);f.microsoft.controls.beforeGraph=async({account,path})=>{if(account==='a'&&path==='/graph/v1.0/me'){reached();await held;}};
 const before=f.microsoft.requests.filter(x=>x.path.startsWith('/graph/')).length,request=operateConnection(a,ra,'inspect');await entered;assert.equal((await operateConnection(a,ra,'disconnect')).status,200);release();assert.notEqual((await request).status,200);f.microsoft.controls.beforeGraph=null;
 assert.equal(f.microsoft.requests.filter(x=>x.path.startsWith('/graph/')).length-before,1);ra=(await listConnections(a)).body.items[0];assert.equal(ra.status,'revoked');assert.equal((await f.owner.query('SELECT count(*)::int n FROM provider_credentials WHERE cave_id=$1',[caveA])).rows[0].n,0);await assert.rejects(()=>f.connectionStore.runDiscoveryJob({...job(ra),authorizationVersion:1}));assert.equal((await f.connectionStore.runDiscoveryJob(job(rb))).resources.length,2);assert.deepEqual((await listConnections(b)).body.items[0],rb);
 }finally{await f.stop();}
});
test('EA-13 AC-01/03: routing collision is atomic, ciphertext cannot move between connections',async()=>{
 const f=await connectionHarness();try{const a=new HttpBrowser(f.appOrigin),b=new HttpBrowser(f.appOrigin);await a.login('alice');await b.login('emile');const ra=await selectConnection(a,await connectAccount(f,a));const duplicate=await connectAccount(f,b,'a');const rejected=await operateConnection(b,duplicate,'resources',{mailboxId:ra.mailboxId,calendarId:ra.calendarId});assert.equal(rejected.status,409);assert.equal(rejected.body.error,'resource_already_routed');assert.equal((await listConnections(b)).body.items[0].version,duplicate.version);assert.equal((await listConnections(a)).body.items[0].version,ra.version);
 const rb=await selectConnection(b,await connectAccount(f,b,'b'));await f.owner.query('UPDATE provider_credentials SET ciphertext=(SELECT ciphertext FROM provider_credentials WHERE cave_id=$1 AND connection_id=$2) WHERE cave_id=$3 AND connection_id=$4',[caveA,ra.id,caveB,rb.id]);assert.equal((await operateConnection(b,rb,'inspect')).body.error,'reconnect_required');const invalid=(await listConnections(b)).body.items.find(x=>x.id===rb.id);assert.equal(invalid.status,'reconnect_required');assert.equal(invalid.authorizationVersion,rb.authorizationVersion+1);assert.equal((await f.owner.query('SELECT count(*)::int n FROM provider_credentials WHERE cave_id=$1 AND connection_id=$2',[caveB,rb.id])).rows[0].n,0);assert.equal((await listConnections(a)).body.items[0].status,'unqualified');
 await assert.rejects(()=>f.owner.query('UPDATE provider_connections SET provider_account_id=$3,version=version+1 WHERE cave_id=$1 AND id=$2',[caveA,ra.id,rb.identity.accountId]),e=>e.code==='23514');
 }finally{await f.stop();}
});
test('EA-13 AC-04/05/06: expiry, refresh refusal, missing permission and real activation guard',async()=>{
 const f=await connectionHarness();try{const a=new HttpBrowser(f.appOrigin);await a.login('alice');f.microsoft.controls.expiresIn=30;let row=await selectConnection(a,await connectAccount(f,a));f.microsoft.controls.refreshMode='invalid';assert.equal((await operateConnection(a,row,'inspect')).body.error,'interaction_required');row=(await listConnections(a)).body.items[0];assert.equal(row.status,'reconnect_required');f.microsoft.controls.refreshMode='valid';f.microsoft.controls.expiresIn=3600;
 assert.equal((await operateConnection(a,row,'inspect')).status,200);row=(await listConnections(a)).body.items[0];f.microsoft.controls.missing.add('calendar');assert.equal((await operateConnection(a,row,'inspect')).status,200);row=(await listConnections(a)).body.items[0];assert.equal(row.calendarId,null);assert.deepEqual(row.missingResources,['calendar']);
 await f.owner.query("UPDATE provider_connections SET version=version+1,expires_at=now()-interval '1 second' WHERE cave_id=$1 AND id=$2",[caveA,row.id]);row=(await listConnections(a)).body.items[0];assert.equal(row.status,'reconnect_required');assert.equal((await operateConnection(a,row,'activate')).status,409);
 const {fixtureOrigin,...realSettings}=f.microsoft.settings,real=new ConnectionStore(f.pool,f.appOrigin,'development',realSettings),s=await a.session(),token=[...a.cookies.get(new URL(f.appOrigin).host)].find(([key])=>key==='encave_session')[1];await assert.rejects(()=>real.operate({token,csrf:s.body.csrf,expectedCave:caveA},row.id,'activate',{expectedVersion:row.version},crypto.randomUUID()),e=>e.code==='not_qualified');
 const plain=await f.owner.query("INSERT INTO provider_connections(cave_id,id,provider,synthetic,label,status,created_by) SELECT cave_id,gen_random_uuid(),'microsoft365',false,'Réel non qualifié','selection_required',created_by FROM provider_connections WHERE cave_id=$1 LIMIT 1 RETURNING id",[caveA]);await assert.rejects(()=>f.owner.query("UPDATE provider_connections SET status='active',version=version+1 WHERE cave_id=$1 AND id=$2",[caveA,plain.rows[0].id]),e=>e.code==='23514');
 }finally{await f.stop();}
});
test('EA-13 AC-04: expired attempt, substituted code and role removal cannot authorize',async()=>{
 const f=await connectionHarness();try{const a=new HttpBrowser(f.appOrigin);await a.login('alice');let start=await beginConnection(a),callback=f.microsoft.approve(start.body.url,'a');await f.owner.query("UPDATE provider_oauth_attempts SET expires_at=now()-interval '1 second' WHERE connection_id=$1",[start.body.id]);assert.match((await a.request(callback)).headers.get('location'),/error=oauth_invalid/);
 const first=await beginConnection(a),second=await beginConnection(a),one=new URL(f.microsoft.approve(first.body.url,'a')),two=new URL(f.microsoft.approve(second.body.url,'a'));one.searchParams.set('code',two.searchParams.get('code'));assert.match((await a.request(one.href)).headers.get('location'),/error=/);
 start=await beginConnection(a);callback=f.microsoft.approve(start.body.url,'a');await f.owner.query("UPDATE members SET role='reader',version=version+1 WHERE cave_id=$1 AND identity_id=(SELECT id FROM identities WHERE subject='alice')",[caveA]);assert.match((await a.request(callback)).headers.get('location'),/error=role_forbidden/);assert.equal((await f.owner.query('SELECT count(*)::int n FROM provider_credentials')).rows[0].n,0);
 }finally{await f.stop();}
});
