import test from 'node:test';
import assert from 'node:assert/strict';
import { chromium,expect } from '@playwright/test';
import { connectionHarness,HttpBrowser,listConnections } from '../helpers/connection-harness.mjs';
import { loginPage } from '../helpers/browser-actions.mjs';
import { recoverConnectionSession } from '../helpers/connection-session-recovery.mjs';
async function connect(page,account='A',label='Accueil synthétique'){await page.getByLabel('Nom de la connexion').fill(label);await page.getByRole('button',{name:'Connecter Microsoft 365',exact:true}).click();await page.getByRole('button',{name:'Compte synthétique '+account,exact:true}).click();await expect(page.getByText('Ressources à choisir',{exact:true})).toBeVisible();}

test('EA-13 R1: compiled browser recovers a lost OAuth command after a new identity session',async()=>{
 const h=await connectionHarness({web:true,compiled:true}),browser=await chromium.launch();try{const page=await browser.newPage();await loginPage(page,h.appOrigin);await recoverConnectionSession(page,h);}finally{await browser.close();await h.stop();}
});
test('EA-13 AC-03/07: compiled UI OAuth, resource selection, restart, two caves and disconnect',async()=>{
 const f=await connectionHarness({web:true,compiled:true}),browser=await chromium.launch();try{const page=await browser.newPage();await loginPage(page,f.appOrigin);await page.getByRole('link',{name:'Connexions',exact:true}).click();await expect(page.getByRole('heading',{name:'Aucune connexion',exact:true})).toBeVisible();await connect(page);
 await page.getByRole('button',{name:'Enregistrer les ressources'}).click();await expect(page.getByRole('main').getByRole('alert')).toContainText('au moins une ressource');await page.getByLabel('Boîte autorisée').selectOption({index:1});await page.getByLabel('Calendrier autorisé').selectOption({index:1});await page.getByRole('button',{name:'Enregistrer les ressources'}).click();await expect(page.getByText('Qualification requise',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Activer la découverte simulée'}).click();await expect(page.getByText('Découverte active — simulation',{exact:true})).toBeVisible();assert.notEqual(await f.restartApi(),f.firstPid);await page.reload();await expect(page.getByText('Découverte active — simulation',{exact:true})).toBeVisible();
 await page.getByLabel('Cave active').selectOption({label:'Cave du Lac — test'});await expect(page.getByRole('heading',{name:'Aucune connexion',exact:true})).toBeVisible();await connect(page,'B','Compte du Lac');await expect(page.getByText('Compte Microsoft synthétique B',{exact:true})).toBeVisible();await page.getByLabel('Cave active').selectOption({label:'Cave des Roches — test'});await expect(page.getByText('Compte Microsoft synthétique A',{exact:true})).toBeVisible();const disconnect=page.getByRole('button',{name:'Déconnecter',exact:true});await disconnect.click();await expect(page.getByRole('button',{name:'Annuler',exact:true})).toBeFocused();await page.keyboard.press('Escape');await expect(disconnect).toBeFocused();await disconnect.click();await page.getByRole('button',{name:'Déconnecter ce compte',exact:true}).click();await expect(page.getByText('Déconnectée',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Activer la découverte simulée'})).toHaveCount(0);
 }finally{await browser.close();await f.stop();}
});
test('EA-13 AC-03/05: lost start reply survives reload and retries the same durable command',async()=>{
 const f=await connectionHarness({web:true,compiled:true}),browser=await chromium.launch();try{const page=await browser.newPage();await loginPage(page,f.appOrigin);await page.goto(f.appOrigin+'/connexions');await page.getByLabel('Nom de la connexion').fill('Réponse perdue');let originalKey;
 await page.route('**/api/connections/microsoft/start',async route=>{originalKey=route.request().headers()['idempotency-key'];await route.fetch();await route.abort('failed');});await page.getByRole('button',{name:'Connecter Microsoft 365',exact:true}).click();await expect(page.getByRole('main').getByRole('alert')).toContainText('n’est pas confirmé');assert.equal((await f.pool.query('SELECT count(*)::int n FROM provider_connections')).rows[0].n,1);await page.unrouteAll();await page.reload();await expect(page.getByRole('button',{name:'Vérifier la commande'})).toBeVisible();await expect(page.getByLabel('Nom de la connexion')).toHaveValue('Réponse perdue');let retryKey;await page.route('**/api/connections/microsoft/start',async route=>{retryKey=route.request().headers()['idempotency-key'];await route.continue();});await page.getByRole('button',{name:'Vérifier la commande'}).click();await page.getByRole('button',{name:'Compte synthétique A'}).click();await expect(page.getByText('Ressources à choisir',{exact:true})).toBeVisible();assert.equal(retryKey,originalKey);assert.equal((await f.pool.query('SELECT count(*)::int n FROM provider_connections')).rows[0].n,1);
 }finally{await browser.close();await f.stop();}
});
test('EA-13 AC-06/07: absent provider configuration and reader leave internal work available',async()=>{
 const f=await connectionHarness({web:true,compiled:true,configured:false}),browser=await chromium.launch();try{const page=await browser.newPage();await loginPage(page,f.appOrigin,'Claire Rey');await page.goto(f.appOrigin+'/connexions');await expect(page.getByRole('heading',{name:'Microsoft non configuré'})).toBeVisible();await expect(page.getByRole('button',{name:'Connecter Microsoft 365',exact:true})).toHaveCount(0);await expect(page.getByText('Consultation seule.',{exact:false})).toBeVisible();await page.getByRole('link',{name:'Demandes',exact:true}).click();await expect(page.getByRole('heading',{name:'Les demandes de votre cave',exact:true})).toBeVisible();
 }finally{await browser.close();await f.stop();}
});
test('EA-13 AC-01/03: uncertain command remains after a403 and retries once rights return',async()=>{
 const f=await connectionHarness({web:true,compiled:true}),browser=await chromium.launch();try{const page=await browser.newPage();await loginPage(page,f.appOrigin);await page.goto(f.appOrigin+'/connexions');await page.getByLabel('Nom de la connexion').fill('Reprise après droits');let firstKey;await page.route('**/api/connections/microsoft/start',async route=>{firstKey=route.request().headers()['idempotency-key'];await route.fetch();await route.abort('failed');});await page.getByRole('button',{name:'Connecter Microsoft 365',exact:true}).click();await expect(page.getByRole('main').getByRole('alert')).toContainText('n’est pas confirmé');await page.unrouteAll();await f.owner.query("UPDATE members SET role='reader',version=version+1 WHERE identity_id=(SELECT id FROM identities WHERE subject='alice')");await page.getByRole('button',{name:'Vérifier la commande'}).click();await expect(page.getByRole('main').getByRole('alert')).toContainText('n’est pas confirmé');await page.reload();await expect(page.getByRole('button',{name:'Vérifier la commande'})).toBeVisible();await f.owner.query("UPDATE members SET role='admin',version=version+1 WHERE identity_id=(SELECT id FROM identities WHERE subject='alice')");let retryKey;await page.route('**/api/connections/microsoft/start',async route=>{retryKey=route.request().headers()['idempotency-key'];await route.continue();});await page.getByRole('button',{name:'Vérifier la commande'}).click();await page.getByRole('button',{name:'Compte synthétique A'}).click();await expect(page.getByText('Ressources à choisir',{exact:true})).toBeVisible();assert.equal(firstKey,retryKey);assert.equal((await f.pool.query('SELECT count(*)::int n FROM provider_connections')).rows[0].n,1);
 }finally{await browser.close();await f.stop();}
});
test('EA-13 AC-01/03: a late response from cave A cannot populate cave B',async()=>{
 const f=await connectionHarness({web:true,compiled:true}),browser=await chromium.launch();try{const context=await browser.newContext(),page=await context.newPage();await loginPage(page,f.appOrigin);await page.goto(f.appOrigin+'/connexions');await connect(page);let release,reached;const held=new Promise(r=>release=r),entered=new Promise(r=>reached=r);await page.route('**/api/connections/*/inspect',async route=>{const response=await route.fetch();reached();await held;await route.fulfill({response});});await page.getByRole('button',{name:'Vérifier la connexion'}).click();await entered;const second=await context.newPage();await second.goto(f.appOrigin+'/connexions');await second.getByLabel('Cave active').selectOption({label:'Cave du Lac — test'});await expect(page.getByRole('heading',{name:'Aucune connexion',exact:true})).toBeVisible();release();await expect(page.getByText('Compte Microsoft synthétique A',{exact:true})).toHaveCount(0);await expect(page.getByLabel('Cave active')).toHaveValue('22222222-2222-4222-8222-222222222222');await expect(page.getByRole('heading',{name:'Commande à vérifier'})).toHaveCount(0);
 }finally{await browser.close();await f.stop();}
});
test('EA-13 AC-03/07: unconfirmed resource choices remain visible after reload',async()=>{
 const f=await connectionHarness({web:true,compiled:true}),browser=await chromium.launch();try{const page=await browser.newPage();await loginPage(page,f.appOrigin);await page.goto(f.appOrigin+'/connexions');await connect(page);await page.getByLabel('Boîte autorisée').selectOption({index:1});await page.getByLabel('Calendrier autorisé').selectOption({index:1});const mailbox=await page.getByLabel('Boîte autorisée').inputValue(),calendar=await page.getByLabel('Calendrier autorisé').inputValue();await page.route('**/api/connections/*/resources',route=>route.abort('failed'));await page.getByRole('button',{name:'Enregistrer les ressources'}).click();await expect(page.getByRole('main').getByRole('alert')).toContainText('n’est pas confirmé');await page.reload();await expect(page.getByRole('button',{name:'Vérifier la commande'})).toBeVisible();await expect(page.getByLabel('Boîte autorisée')).toHaveValue(mailbox);await expect(page.getByLabel('Calendrier autorisé')).toHaveValue(calendar);await expect(page.getByLabel('Boîte autorisée')).toBeDisabled();await page.unrouteAll();await page.getByRole('button',{name:'Vérifier la commande'}).click();await expect(page.getByText('Qualification requise',{exact:true})).toBeVisible();assert.equal((await f.pool.query("SELECT count(*)::int n FROM provider_connection_commands WHERE kind='select'")).rows[0].n,1);
 }finally{await browser.close();await f.stop();}
});
