import test from 'node:test';
import assert from 'node:assert/strict';
import { chromium,expect } from '@playwright/test';
import { caseHarness } from '../helpers/case-harness.mjs';
import { loginPage } from '../helpers/browser-actions.mjs';
import { fillManual,manualInput,seedQueue } from '../helpers/manual-harness.mjs';
import { HttpBrowser } from '../helpers/identity-harness.mjs';
import { caveA,caveB } from '../../../packages/tooling/src/identity-test-database.ts';
async function setup(t){const h=await caseHarness();let browser;t.after(async()=>{if(browser)await browser.close();await h.stop();});browser=await chromium.launch();const page=await browser.newPage();await loginPage(page,h.appOrigin);await page.goto(h.appOrigin+'/demandes');await expect(page.getByRole('heading',{name:'Votre première demande commence ici'})).toBeVisible();return{h,browser,page};}

test('manual browser validation and persisted dossier survive reload API restart and a separate reader session',async t=>{
  const {h,browser,page}=await setup(t);await page.getByRole('link',{name:'Nouvelle demande',exact:true}).click();await page.getByRole('button',{name:'Enregistrer la demande',exact:true}).click();await expect(page.getByRole('main').getByRole('alert')).toContainText('Vérifiez les informations');await expect(page.getByLabel('Nom du client',{exact:true})).toHaveAttribute('aria-invalid','true');
  const note='<img src=x onerror="window.injected=true"> — compte rendu fictif';await fillManual(page,{note});await page.getByLabel('Budget CHF (facultatif)').fill('150,25');await page.getByLabel('Ce budget concerne (si renseigné)').selectOption('group');await page.getByRole('button',{name:'Enregistrer la demande',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Demande enregistrée'})).toContainText('Demande enregistrée');await expect(page.getByRole('heading',{name:'Camille Fictive',exact:true})).toBeVisible();await expect(page.locator('.message-body')).toHaveText(note);assert.equal(await page.evaluate(()=>window.injected),undefined);await expect(page.locator('.facts')).toContainText('150.25 CHF pour le groupe');await expect(page.locator('.facts')).toContainText('Alice Martin');
  const url=page.url();await page.reload();await expect(page.locator('.message-body')).toHaveText(note);assert.notEqual(await h.restartApi(),h.firstPid);await page.reload();await expect(page.locator('.message-body')).toHaveText(note);
  const reader=await browser.newPage();await loginPage(reader,h.appOrigin,'Claire Rey');await reader.goto(url);await expect(reader.locator('.message-body')).toHaveText(note);await reader.goto(h.appOrigin+'/demandes');await expect(reader.getByRole('link',{name:'Nouvelle demande',exact:true})).toHaveCount(0);
  assert.equal((await h.pool.query('SELECT count(*)::int n FROM inquiries')).rows[0].n,1);assert.equal((await h.pool.query('SELECT count(*)::int n FROM actions')).rows[0].n,0);
});
test('a lost success response retains the exact command across reload and resolves without a second dossier',async t=>{
  const {h,page}=await setup(t);await page.getByRole('link',{name:'Nouvelle demande',exact:true}).click();await fillManual(page);let intercepted=false;
  await page.route('**/api/inquiries/manual',async route=>{if(!intercepted){intercepted=true;const response=await route.fetch();assert.equal(response.status(),201);await route.abort('failed');}else await route.continue();});
  await page.getByRole('button',{name:'Enregistrer la demande',exact:true}).click();await expect(page.getByRole('main').getByRole('alert')).toContainText('L’enregistrement n’est pas confirmé');await expect(page.getByLabel('Nom du client',{exact:true})).toHaveValue('Camille Fictive');await expect(page.getByLabel('Nom du client',{exact:true})).toBeDisabled();assert.equal((await h.pool.query('SELECT count(*)::int n FROM inquiries')).rows[0].n,1);
  await page.reload();await expect(page.getByRole('button',{name:'Vérifier l’enregistrement',exact:true})).toBeVisible();await expect(page.getByLabel('Nom du client',{exact:true})).toHaveValue('Camille Fictive');await page.getByRole('button',{name:'Vérifier l’enregistrement',exact:true}).click();await expect(page.getByRole('heading',{name:'Camille Fictive',exact:true})).toBeVisible();assert.equal((await h.pool.query('SELECT count(*)::int n FROM inquiries')).rows[0].n,1);assert.equal((await h.pool.query('SELECT count(*)::int n FROM inquiry_commands')).rows[0].n,1);
});
test('twenty real inquiries retain filters sorting and scroll position after opening their dossier',async t=>{
  const {h,page}=await setup(t),http=new HttpBrowser(h.appOrigin);await http.login('alice');const ids=await seedQueue(http,20);await page.reload();await expect(page.locator('.inquiry-card')).toHaveCount(20);await page.getByLabel('Trier les demandes').selectOption('oldest');await expect(page.locator('.inquiry-card h2 a').first()).toHaveText('Visiteur fictif 01');
  const link=page.getByRole('link',{name:'Ouvrir le dossier de Visiteur fictif 15',exact:true});await link.scrollIntoViewIfNeeded();const oldY=await page.evaluate(()=>scrollY);await link.click();await expect(page.getByRole('heading',{name:'Visiteur fictif 15',exact:true})).toBeVisible();assert.ok(page.url().endsWith(ids[14]));await page.getByRole('link',{name:'Retour à la liste',exact:true}).click();await expect(page.locator('.inquiry-card')).toHaveCount(20);await expect(page.getByLabel('Trier les demandes')).toHaveValue('oldest');await expect.poll(()=>page.evaluate(()=>scrollY)).toBe(oldY);
  await page.getByLabel('Rechercher un client ou un besoin').fill('Visiteur fictif 15');await expect(page.locator('.inquiry-card')).toHaveCount(1);await page.getByRole('link',{name:'Ouvrir le dossier de Visiteur fictif 15',exact:true}).click();await expect(page.locator('.message-body')).toBeVisible();await page.getByRole('link',{name:'Retour à la liste',exact:true}).click();await expect(page.getByLabel('Rechercher un client ou un besoin')).toHaveValue('Visiteur fictif 15');await expect(page.locator('.inquiry-card')).toHaveCount(1);
});
test('late lists and unsaved forms remain isolated when the cave changes',async t=>{
  const {h,page}=await setup(t),http=new HttpBrowser(h.appOrigin);await http.login('alice');await seedQueue(http,1);let release,heldResolve;const hold=new Promise(r=>release=r),held=new Promise(r=>heldResolve=r);let once=false;
  await page.route('**/api/inquiries?*',async route=>{if(!once){once=true;const response=await route.fetch();heldResolve();await hold;await route.fulfill({response});}else await route.continue();});await page.reload();await held;await page.getByLabel('Changer de cave',{exact:true}).selectOption(caveB);await expect(page.getByTestId('active-cave')).toHaveText('Cave du Lac — test');release();await expect(page.getByRole('heading',{name:'Votre première demande commence ici'})).toBeVisible();await expect(page.getByText('Visiteur fictif 01',{exact:true})).toHaveCount(0);await page.unrouteAll({behavior:'wait'});
  await page.getByRole('link',{name:'Nouvelle demande',exact:true}).click();await fillManual(page,{contactName:'Brouillon uniquement Lac'});await page.getByLabel('Changer de cave',{exact:true}).selectOption(caveA);await expect(page.getByRole('dialog')).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByLabel('Nom du client',{exact:true})).toHaveValue('Brouillon uniquement Lac');await page.getByLabel('Changer de cave',{exact:true}).selectOption(caveA);await page.getByRole('button',{name:'Abandonner et changer de cave'}).click();await expect(page.getByTestId('active-cave')).toHaveText('Cave des Roches — test');await page.getByRole('link',{name:'Nouvelle demande',exact:true}).click();await expect(page.getByLabel('Nom du client',{exact:true})).toHaveValue('');
});
