import test from 'node:test';
import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { chromium,expect } from '@playwright/test';
import { caseHarness } from '../helpers/case-harness.mjs';
import { HttpBrowser } from '../helpers/identity-harness.mjs';
import { loginPage } from '../helpers/browser-actions.mjs';
import { configureForm,formDefinition,fillPublic,challenge,submitPublic } from '../helpers/public-form-harness.mjs';
import { manualRead } from '../helpers/manual-harness.mjs';
async function setup(t,definition={}){const h=await caseHarness();let browser;t.after(async()=>{if(browser)await browser.close();await h.stop();});const staff=new HttpBrowser(h.appOrigin);await staff.login('alice');const form=await configureForm(staff,{definition:formDefinition(definition)});assert.equal(form.status,200);browser=await chromium.launch();return{...h,staff,form:form.body,browser,page:await browser.newPage()};}
test('a real cave site link opens a visitor form without login and persists a reply channel across API restart',async t=>{
 const h=await setup(t),site=createServer((_q,r)=>r.end('<!doctype html><html lang="fr"><title>Cave fictive</title><h1>Cave fictive</h1>'+h.form.html+'</html>'));await new Promise(r=>site.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>site.close(r)));const page=h.page;await page.goto('http://127.0.0.1:'+site.address().port);await page.getByRole('link',{name:'Demander une visite'}).click();await expect(page.getByRole('heading',{name:'Demander une visite',exact:true})).toBeVisible();assert.equal((await page.context().cookies()).length,0);
 const hostile='<script>window.visitorInjected=true</script> Besoin fictif';await fillPublic(page,{contactEmail:null,contactPhone:'+41 21 555 01 02',need:hostile});await page.getByLabel('Date souhaitée (facultatif)',{exact:true}).fill('2026-10-15');await page.getByLabel('Nombre de personnes (facultatif)',{exact:true}).fill('12');await page.getByLabel('Budget en CHF (facultatif)',{exact:true}).fill('120,50');await page.getByLabel('Ce budget concerne (facultatif)',{exact:true}).selectOption('group');await page.getByRole('button',{name:'Envoyer ma demande',exact:true}).click();await expect(page.getByRole('heading',{name:'Demande reçue',exact:true})).toBeVisible();const reference=await page.locator('.public-reference strong').innerText();assert.equal(await page.evaluate(()=>window.visitorInjected),undefined);await page.reload();await expect(page.getByRole('heading',{name:'Demande reçue',exact:true})).toBeVisible();assert.equal(await page.locator('.public-reference strong').innerText(),reference);
 const pid=await h.restartApi();assert.notEqual(pid,h.firstPid);const list=(await manualRead(h.staff)).body;assert.equal(list.total,1);const row=list.items[0];assert.equal(row.contactPhone,'+41 21 555 01 02');assert.equal(row.budgetMinor,12050);assert.equal(row.requestedDate,'2026-10-15');assert.equal(row.participants,12);const staffPage=await h.browser.newPage();await loginPage(staffPage,h.appOrigin);await staffPage.goto(h.appOrigin+'/demandes?id='+row.id);await expect(staffPage.getByText('Formulaire du site',{exact:true})).toBeVisible();await expect(staffPage.getByText(/Le visiteur, sans compte/)).toBeVisible();await expect(staffPage.locator('.message-body')).toHaveText(hostile);assert.equal(await staffPage.evaluate(()=>window.visitorInjected),undefined);assert.equal((await page.request.get(h.appOrigin+'/api/inquiries/'+row.id+'/dossier')).status(),401);
});
test('lost accepted response survives disabled form, reload and API restart with the exact same submission',async t=>{
 const h=await setup(t),page=h.page;await page.goto(h.form.url);await fillPublic(page);const commands=[];page.on('request',r=>{if(r.method()==='POST'&&r.url().includes('/api/public/forms/'))commands.push(r.postData());});let first=true;await page.route('**/api/public/forms/*',async route=>{if(route.request().method()==='POST'&&first){first=false;const r=await route.fetch();assert.equal(r.status(),201);await route.abort('failed');}else await route.continue();});await page.getByRole('button',{name:'Envoyer ma demande',exact:true}).click();await expect(page.getByRole('main').getByRole('alert')).toContainText('n’est pas confirmée');assert.equal((await h.pool.query('SELECT count(*)::int n FROM inquiries')).rows[0].n,1);
 await configureForm(h.staff,{expectedVersion:1,enabled:false});await page.getByRole('button',{name:'Vérifier la réception',exact:true}).click();await expect(page.getByRole('main').getByRole('alert')).toContainText('indisponible');await expect(page.getByLabel('Votre nom',{exact:true})).toBeDisabled();await page.reload();await expect(page.getByRole('button',{name:'Vérifier la réception',exact:true})).toBeVisible();await expect(page.getByLabel('Votre nom',{exact:true})).toHaveValue('Camille Visiteur');
 await configureForm(h.staff,{expectedVersion:2,enabled:true});assert.notEqual(await h.restartApi(),h.firstPid);await h.owner.query("UPDATE public_form_challenges SET issued_at=now()-interval '1 hour',expires_at=now()-interval '1 second'");await page.getByRole('button',{name:'Vérifier la réception',exact:true}).click();await expect(page.getByRole('heading',{name:'Demande reçue',exact:true})).toBeVisible();assert.equal(commands.length,3);assert.deepEqual(commands,[commands[0],commands[0],commands[0]]);assert.equal((await h.pool.query('SELECT count(*)::int n FROM inquiries')).rows[0].n,1);
});
test('public validation preserves input and an expired challenge can be refreshed without inventing a receipt',async t=>{
 const h=await setup(t),page=h.page;await page.goto(h.form.url);await page.getByRole('button',{name:'Envoyer ma demande',exact:true}).click();await expect(page.getByRole('main').getByRole('alert')).toContainText('Vérifiez');await expect(page.getByLabel('Votre nom',{exact:true})).toBeEnabled();await expect(page.getByLabel('Adresse e-mail',{exact:true})).toHaveAttribute('aria-invalid','true');await fillPublic(page);await h.owner.query("UPDATE public_form_challenges SET issued_at=now()-interval '1 hour',expires_at=now()-interval '1 second'");await page.getByRole('button',{name:'Envoyer ma demande',exact:true}).click();await expect(page.getByRole('button',{name:'Actualiser en conservant ma saisie'})).toBeVisible();assert.equal((await h.pool.query('SELECT count(*)::int n FROM inquiries')).rows[0].n,0);await page.getByRole('button',{name:'Actualiser en conservant ma saisie'}).click();await expect(page.getByLabel('Votre nom',{exact:true})).toHaveValue('Camille Visiteur');await page.getByRole('button',{name:'Envoyer ma demande',exact:true}).click();await expect(page.getByRole('heading',{name:'Demande reçue',exact:true})).toBeVisible();
});
test('SQL throttling survives a real process restart and Retry-After reaches the browser through Next',async t=>{
 const h=await setup(t,{attemptLimitPerMinute:1}),c=(await challenge(h)).body;assert.equal((await submitPublic(h,c)).status,201);assert.notEqual(await h.restartApi(),h.firstPid);const limited=await submitPublic(h,c);assert.equal(limited.status,429);assert.ok(Number(limited.retryAfter)>0);assert.equal((await h.pool.query('SELECT count(*)::int n FROM inquiries')).rows[0].n,1);
});
