import test,{after} from 'node:test';
import assert from 'node:assert/strict';
import { mkdir,readFile,writeFile } from 'node:fs/promises';
import { randomBytes,createHash } from 'node:crypto';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { chromium,expect } from '@playwright/test';
import { connectionHarness,HttpBrowser,connectAccount,selectConnection,beginConnection,listConnections,operateConnection,caveA } from '../helpers/connection-harness.mjs';
import { loginPage } from '../helpers/browser-actions.mjs';
import { recoverConnectionSession } from '../helpers/connection-session-recovery.mjs';
import { zoomBrowser } from '../helpers/ux-browser.mjs';
const root=fileURLToPath(new URL('../../../',import.meta.url)),directory=join(root,'.local/ux/EA-13',`${Date.now()}-${randomBytes(3).toString('hex')}`);await mkdir(directory,{recursive:true});
const evidence={note:'Actual Chromium, compiled API, PostgreSQL and MSAL with explicitly synthetic Microsoft transport. No real account, send, sync or calendar write.',captures:[],measurements:[]};
async function capture(page,name,serverState,bytes,extra={}){const path=join(directory,name+'.png');if(bytes)await writeFile(path,bytes);else await page.screenshot({path,fullPage:true,animations:'disabled'});evidence.captures.push({name,path,viewport:page.viewportSize(),serverState,sha256:createHash('sha256').update(await readFile(path)).digest('hex'),...extra});}
after(async()=>{await writeFile(join(directory,'manifest.json'),JSON.stringify(evidence,null,2)+'\n');await writeFile(join(root,'.local/ux/EA-13/latest.json'),JSON.stringify({directory,verdict:'see_test_log'})+'\n');console.log('Connection UX captures: '+evidence.captures.length);});
test('EA-13 R1 UX: a renewed session can recover and finish the durable connection on mobile',async t=>{
 const h=await setup(t),page=h.page;await page.setViewportSize({width:390,height:1000});await recoverConnectionSession(page,h,async name=>{await inspect(page,name);await capture(page,name+'-mobile','Lost start response, renewed EnCave session, original durable connection recovered without reusing the old OAuth flow.');});
});
async function setup(t,{zoom=false,configured=true}={}){const h=await connectionHarness({web:true,compiled:true,configured});let browser;t.after(async()=>{if(browser){if(zoom)await browser.stop();else await browser.close();}await h.stop();});const staff=new HttpBrowser(h.appOrigin);await staff.login('alice');browser=zoom?await zoomBrowser():await chromium.launch();const page=zoom?browser.context.pages()[0]:await browser.newPage({viewport:{width:1440,height:1000}});await loginPage(page,h.appOrigin);return{...h,staff,browser,page};}
async function inspect(page,label){const value=await page.evaluate(()=>{
 const visible=e=>{const r=e.getBoundingClientRect();return r.width&&r.height&&!e.closest('[aria-hidden="true"]');},bg=e=>{for(let p=e;p;p=p.parentElement){const c=getComputedStyle(p).backgroundColor;if(c!=='rgba(0, 0, 0, 0)'&&c!=='transparent')return c;}return'rgb(255,255,255)';},lum=c=>c.match(/[\d.]+/g).slice(0,3).map(Number).map(n=>n/255).map(n=>n<=.04045?n/12.92:((n+.055)/1.055)**2.4).reduce((s,n,i)=>s+n*[.2126,.7152,.0722][i],0),ratio=(a,b)=>(Math.max(lum(a),lum(b))+.05)/(Math.min(lum(a),lum(b))+.05);
 return{width:document.documentElement.clientWidth,scrollWidth:document.documentElement.scrollWidth,targets:[...document.querySelectorAll('button,input,textarea,select,a.button,a.error-link')].filter(visible).map(e=>{const r=e.getBoundingClientRect();return{width:r.width,height:r.height,left:r.left,right:r.right};}),contrast:Math.min(...[...document.querySelectorAll('h1,h2,h3,p,label,dt,dd,strong,.button')].filter(visible).map(e=>ratio(getComputedStyle(e).color,bg(e)))),borders:[...document.querySelectorAll('input,textarea,select')].filter(visible).map(e=>ratio(getComputedStyle(e).borderTopColor,bg(e)))};
 });assert.ok(value.scrollWidth<=value.width+1,label+': horizontal overflow');for(const r of value.targets){assert.ok(r.width>=43.9&&r.height>=43.9,label+': target44');assert.ok(r.left>=-1&&r.right<=value.width+1,label+': offscreen');}assert.ok(value.contrast>=4.5,label+': text contrast');for(const c of value.borders)assert.ok(c>=3,label+': input contrast');evidence.measurements.push({label,...value});}
async function zoomCapture(page,name){const cdp=await page.context().newCDPSession(page);try{await page.evaluate(()=>scrollTo(0,0));for(let n=0;n<24;n++){await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const m=await page.evaluate(()=>({scrollY,innerWidth,innerHeight,height:document.documentElement.scrollHeight,devicePixelRatio}));const result=await cdp.send('Page.captureScreenshot',{format:'png',fromSurface:true,captureBeyondViewport:false});await capture(page,`${name}-${n+1}`,'Actual browser zoom; overlapping visible viewport, full vertical coverage.',Buffer.from(result.data,'base64'),m);if(m.scrollY+m.innerHeight>=m.height-1)return;await page.evaluate(()=>scrollBy(0,Math.floor(innerHeight*.9)));}assert.fail('Zoom traversal exhausted');}finally{await cdp.detach();await page.evaluate(()=>scrollTo(0,0));}}
test('EA-13 UX: actual connection workflow, responsive, keyboard, target and contrast checks',async t=>{
 const h=await setup(t),page=h.page;await page.goto(h.appOrigin+'/connexions');await expect(page.getByRole('heading',{name:'Aucune connexion',exact:true})).toBeVisible();for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:1000});await inspect(page,'empty-'+width);await capture(page,'empty-'+width,'Configured synthetic provider; no connection yet.');}
 await page.getByLabel('Nom de la connexion').fill('Accueil de la cave');await page.getByRole('button',{name:'Connecter Microsoft 365',exact:true}).focus();await page.keyboard.press('Enter');await page.getByRole('button',{name:'Compte synthétique A'}).click();await expect(page.getByText('Ressources à choisir',{exact:true})).toBeVisible();await page.setViewportSize({width:390,height:1000});await page.getByRole('button',{name:'Enregistrer les ressources'}).click();await expect(page.getByLabel('Boîte autorisée')).toBeFocused();await expect(page.getByRole('main').getByRole('alert')).toContainText('au moins une ressource');await capture(page,'selection-invalid-mobile','Actual client validation, linked descriptions on selectors, focus on first choice.');
 await page.getByLabel('Boîte autorisée').selectOption({index:1});await page.getByLabel('Calendrier autorisé').selectOption({index:1});await page.getByRole('button',{name:'Enregistrer les ressources'}).click();await expect(page.getByText('Qualification requise',{exact:true})).toBeVisible();for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:1000});await inspect(page,'selected-'+width);await capture(page,'selected-'+width,'Persisted own-account resources, unqualified, unsupported writes explicit.');}
 await page.getByRole('button',{name:'Activer la découverte simulée'}).focus();await page.keyboard.press('Enter');await expect(page.getByText('Découverte active — simulation',{exact:true})).toBeVisible();await capture(page,'active-desktop','Synthetic discovery only; no synchronization or external business effects.');await page.setViewportSize({width:390,height:1000});const button=page.getByRole('button',{name:'Déconnecter',exact:true});await button.focus();await page.keyboard.press('Enter');await expect(page.getByRole('button',{name:'Annuler',exact:true})).toBeFocused();await capture(page,'disconnect-dialog-mobile','Real modal, cave and account shown, local disconnect limits explicit, safe initial focus.');await page.keyboard.press('Tab');await expect(page.getByRole('button',{name:'Déconnecter ce compte',exact:true})).toBeFocused();const outline=await page.getByRole('button',{name:'Déconnecter ce compte',exact:true}).evaluate(e=>getComputedStyle(e).outlineWidth);assert.equal(outline,'3px');await capture(page,'disconnect-keyboard-mobile','Tab stays inside modal with 3px visible focus.');await page.keyboard.press('Escape');await expect(button).toBeFocused();await button.click();await page.getByRole('button',{name:'Déconnecter ce compte',exact:true}).click();await expect(page.getByText('Déconnectée',{exact:true})).toBeVisible();await inspect(page,'revoked-mobile');await capture(page,'revoked-mobile','SQL credentials removed and new actions disabled; historical account remains visible.');
});
test('EA-13 UX: consent, health errors, pending response, absent configuration and reader',async t=>{
 const h=await setup(t),page=h.page;await page.goto(h.appOrigin+'/connexions');await page.setViewportSize({width:390,height:1000});await page.getByLabel('Nom de la connexion').fill('Autorisation de la cave');await page.getByRole('button',{name:'Connecter Microsoft 365',exact:true}).click();await page.getByRole('button',{name:'Consentement administrateur requis',exact:true}).click();await expect(page.getByText('Consentement administrateur requis',{exact:true})).toBeVisible();await capture(page,'admin-consent-mobile','Actual synthetic OAuth denial, server state admin_consent_required; no bypass.');await page.getByRole('button',{name:'Reconnecter',exact:true}).click();await page.getByRole('button',{name:'Refuser le consentement'}).click();await expect(page.getByText('Consentement refusé',{exact:true})).toBeVisible();await capture(page,'consent-denied-mobile','Actual access_denied and inactive connection, reusable reconnect action.');
 await page.getByRole('button',{name:'Reconnecter',exact:true}).click();await page.getByRole('button',{name:'Compte synthétique A'}).click();await expect(page.getByText('Ressources à choisir',{exact:true})).toBeVisible();h.microsoft.controls.missing.add('calendar');await page.getByRole('button',{name:'Vérifier la connexion'}).click();await expect(page.getByText('Ressources indisponibles : calendrier.',{exact:false})).toBeVisible();await capture(page,'missing-permission-mobile','Real synthetic Graph403 for calendar; mailbox remains permitted.');h.microsoft.controls.missing.clear();await page.getByRole('button',{name:'Reconnecter',exact:true}).click();await page.getByRole('button',{name:'Compte synthétique B'}).click();await expect(page.getByText('Reconnexion requise',{exact:true})).toBeVisible();await capture(page,'wrong-account-mobile','Verified different identity rejected, original identity remains immutable.');await page.getByRole('button',{name:'Reconnecter',exact:true}).click();await page.getByRole('button',{name:'Compte synthétique A'}).click();await expect(page.getByText('Ressources à choisir',{exact:true})).toBeVisible();
 await h.owner.query("UPDATE provider_connections SET version=version+1,expires_at=now()-interval '1 second'");await page.reload();await expect(page.getByText('Reconnexion requise',{exact:true})).toBeVisible();await capture(page,'expired-mobile','Actual stored token expiry, reconnect state with bounded health check available.');await page.getByRole('button',{name:'Vérifier la connexion'}).click();await expect(page.getByText('Ressources à choisir',{exact:true})).toBeVisible();h.microsoft.controls.graphMode='rate';await page.getByRole('button',{name:'Vérifier la connexion'}).click();await expect(page.getByRole('main').getByRole('alert')).toContainText('limite');await capture(page,'rate-limited-mobile','Real synthetic Graph429; no success displayed.');h.microsoft.controls.graphMode='valid';await page.getByRole('button',{name:'Actualiser',exact:true}).click();await expect(page.getByText('Connexion en erreur',{exact:true})).toBeVisible();await capture(page,'health-error-mobile','Persisted individual last error after throttling.');
 let release;const held=new Promise(r=>release=r);await page.route('**/api/connections/*/inspect',async route=>{await held;await route.abort('failed');});await page.getByRole('button',{name:'Vérifier la connexion'}).click();await expect(page.getByRole('status')).toContainText('Action en cours');await capture(page,'pending-mobile','Transport held before API; command persisted, controls locked.');release();await expect(page.getByRole('main').getByRole('alert')).toContainText('n’est pas confirmé');await capture(page,'uncertain-mobile','Injected transport failure; identical durable command retained.');await page.unrouteAll({behavior:'wait'});await page.getByRole('button',{name:'Vérifier la commande'}).click();await expect(page.getByRole('heading',{name:'Commande à vérifier'})).toHaveCount(0);
 const reader=await h.browser.newPage({viewport:{width:390,height:1000}});await loginPage(reader,h.appOrigin,'Claire Rey');await reader.goto(h.appOrigin+'/connexions');await expect(reader.getByText('Consultation seule.',{exact:false})).toBeVisible();await inspect(reader,'reader-mobile');await capture(reader,'reader-mobile','Authenticated reader sees scoped health, no mutation controls.');await reader.close();
});
test('EA-13 UX: absent configuration is factual and actual zoom200/400 remains usable',async t=>{
 const h=await setup(t,{zoom:true}),page=h.page;await selectConnection(h.staff,await connectAccount(h,h.staff));await page.goto(h.appOrigin+'/connexions');await expect(page.getByText('Qualification requise',{exact:true})).toBeVisible();await page.setViewportSize({width:1280,height:1000});for(const factor of [2,4]){assert.ok(Math.abs(await h.browser.zoom(page,factor)-factor)<1e-12);await expect.poll(()=>page.evaluate(()=>innerWidth)).toBe(1280/factor);await inspect(page,'zoom'+factor*100);await zoomCapture(page,'zoom'+factor*100);await h.browser.zoom(page,1);}
 const none=await connectionHarness({web:true,compiled:true,configured:false});try{const q=await h.browser.context.newPage();await loginPage(q,none.appOrigin);await q.goto(none.appOrigin+'/connexions');await expect(q.getByRole('heading',{name:'Microsoft non configuré'})).toBeVisible();await q.setViewportSize({width:390,height:1000});await inspect(q,'not-configured-mobile');await capture(q,'not-configured-mobile','Real runtime without Microsoft configuration; manual intake remains available.');await q.close();}finally{await none.stop();}
});
test('EA-13 UX: saved label and resource choices stay visible during uncertain recovery',async t=>{
 const h=await setup(t),page=h.page;await page.goto(h.appOrigin+'/connexions');await page.setViewportSize({width:390,height:1000});await page.getByLabel('Nom de la connexion').fill('Accueil à reconnecter');await page.route('**/api/connections/microsoft/start',route=>route.abort('failed'));await page.getByRole('button',{name:'Connecter Microsoft 365',exact:true}).click();await expect(page.getByRole('main').getByRole('alert')).toContainText('n’est pas confirmé');await page.reload();await expect(page.getByLabel('Nom de la connexion')).toHaveValue('Accueil à reconnecter');await capture(page,'restored-label-mobile','Transport aborted before API, saved label visible after reload, original command locked.');await page.unrouteAll();await page.getByRole('button',{name:'Vérifier la commande'}).click();await page.getByRole('button',{name:'Compte synthétique A'}).click();await expect(page.getByText('Ressources à choisir',{exact:true})).toBeVisible();await page.getByLabel('Boîte autorisée').selectOption({index:1});await page.getByLabel('Calendrier autorisé').selectOption({index:1});const mailbox=await page.getByLabel('Boîte autorisée').inputValue();await page.route('**/api/connections/*/resources',route=>route.abort('failed'));await page.getByRole('button',{name:'Enregistrer les ressources'}).click();await expect(page.getByRole('main').getByRole('alert')).toContainText('n’est pas confirmé');await page.reload();await expect(page.getByLabel('Boîte autorisée')).toHaveValue(mailbox);await expect(page.getByLabel('Boîte autorisée')).toBeDisabled();await inspect(page,'restored-resources-mobile');await capture(page,'restored-resources-mobile','Uncommitted selections restored from scoped durable command, not overwritten by older SQL values.');await page.unrouteAll();await page.getByRole('button',{name:'Vérifier la commande'}).click();await expect(page.getByText('Qualification requise',{exact:true})).toBeVisible();
});
