import test,{after} from 'node:test';
import assert from 'node:assert/strict';
import { mkdir,readFile,writeFile } from 'node:fs/promises';
import { randomBytes,createHash } from 'node:crypto';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { chromium,expect } from '@playwright/test';
import { caseHarness } from '../helpers/case-harness.mjs';
import { loginPage } from '../helpers/browser-actions.mjs';
import { fillManual,seedQueue } from '../helpers/manual-harness.mjs';
import { HttpBrowser } from '../helpers/identity-harness.mjs';
import { zoomBrowser } from '../helpers/ux-browser.mjs';
const root=fileURLToPath(new URL('../../../',import.meta.url)),directory=join(root,'.local/ux/EA-11',`${Date.now()}-${randomBytes(3).toString('hex')}`);
await mkdir(directory,{recursive:true});const evidence={note:'Actual browser, synthetic data and real API/PostgreSQL. Transport faults explicitly labeled. No external integration.',captures:[],measurements:[]};
async function capture(page,name,serverState,bytes,extra={}){const path=join(directory,name+'.png');if(bytes)await writeFile(path,bytes);else await page.screenshot({path,fullPage:true,animations:'disabled'});evidence.captures.push({name,path,viewport:page.viewportSize(),serverState,sha256:createHash('sha256').update(await readFile(path)).digest('hex'),...extra});}
after(async()=>{await writeFile(join(directory,'manifest.json'),JSON.stringify(evidence,null,2)+'\n');await writeFile(join(root,'.local/ux/EA-11/latest.json'),JSON.stringify({directory,verdict:'see_test_log'})+'\n');console.log('Manual UX captures: '+evidence.captures.length);});
async function inspect(page,label){const result=await page.evaluate(()=>{
  const visible=e=>{const b=e.getBoundingClientRect();return b.width&&b.height&&!e.closest('dialog:not([open])');};
  const bg=e=>{for(let p=e;p;p=p.parentElement){const c=getComputedStyle(p).backgroundColor;if(c!=='rgba(0, 0, 0, 0)'&&c!=='transparent')return c;}return'rgb(255,255,255)';};
  const lum=c=>c.match(/[\d.]+/g).slice(0,3).map(Number).map(n=>n/255).map(n=>n<=.04045?n/12.92:((n+.055)/1.055)**2.4).reduce((s,n,i)=>s+n*[.2126,.7152,.0722][i],0);
  const ratio=(a,b)=>{const x=lum(a),y=lum(b);return(Math.max(x,y)+.05)/(Math.min(x,y)+.05);};
  const controls=[...document.querySelectorAll('button,input,select,textarea,a.button,nav a,.inquiry-card h2 a')].filter(visible).map(e=>{const r=e.getBoundingClientRect();return{width:r.width,height:r.height,left:r.left,right:r.right};});
  const pairs=[...document.querySelectorAll('h1,h2,p,label,dt,dd,strong,.inquiry-badge,.button,nav a')].filter(visible).map(e=>ratio(getComputedStyle(e).color,bg(e)));
  const borders=[...document.querySelectorAll('input,textarea,select')].filter(visible).map(e=>ratio(getComputedStyle(e).borderTopColor,bg(e)));
  return{width:document.documentElement.clientWidth,scrollWidth:document.documentElement.scrollWidth,controls,minimumTextContrast:Math.min(...pairs),minimumFieldContrast:borders.length?Math.min(...borders):null};
});assert.ok(result.scrollWidth<=result.width+1,label+': horizontal overflow');for(const b of result.controls){assert.ok(b.width>=43.9&&b.height>=43.9,label+': target below44');assert.ok(b.left>=-1&&b.right<=result.width+1,label+': offscreen control');}assert.ok(result.minimumTextContrast>=4.5,label+': text contrast');if(result.minimumFieldContrast!==null)assert.ok(result.minimumFieldContrast>=3,label+': field border');evidence.measurements.push({label,...result});}
async function tabTo(page,target){for(let i=0;i<70;i++){if(await target.evaluate(e=>document.activeElement===e))return;await page.keyboard.press('Tab');}assert.fail('Keyboard traversal did not reach expected control');}
async function zoomCapture(page,name){const cdp=await page.context().newCDPSession(page);try{await page.evaluate(()=>scrollTo(0,0));for(let n=0;n<24;n++){await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const m=await page.evaluate(()=>({scrollY,innerWidth,innerHeight,height:document.documentElement.scrollHeight,devicePixelRatio}));const shot=await cdp.send('Page.captureScreenshot',{format:'png',fromSurface:true,captureBeyondViewport:false});await capture(page,`${name}-${n+1}`,'Real browser zoom; overlapping visible viewport, full vertical coverage.',Buffer.from(shot.data,'base64'),m);if(m.scrollY+m.innerHeight>=m.height-1)return;await page.evaluate(()=>scrollBy(0,Math.floor(innerHeight*.9)));}assert.fail('Zoom traversal exceeded bound');}finally{await cdp.detach();await page.evaluate(()=>scrollTo(0,0));}}

test('manual list form and dossier expose real states at all viewports and through the keyboard',async t=>{
  const h=await caseHarness();let browser;t.after(async()=>{if(browser)await browser.close();await h.stop();});browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1440,height:1000}});await loginPage(page,h.appOrigin);await page.goto(h.appOrigin+'/demandes');await expect(page.getByRole('heading',{name:'Votre première demande commence ici'})).toBeVisible();
  for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:1000});await inspect(page,'empty-'+width);await capture(page,'empty-'+width,'Empty real cave, no dossiers.');}
  const http=new HttpBrowser(h.appOrigin);await http.login('alice');await seedQueue(http,20);await page.reload();await expect(page.locator('.inquiry-card')).toHaveCount(20);await inspect(page,'queue-desktop');await capture(page,'queue-20-desktop','20 real synthetic manual dossiers, default intervention/date/age sort.');
  await page.setViewportSize({width:390,height:844});await inspect(page,'queue-mobile');await capture(page,'queue-20-mobile','Same 20 persisted dossiers, responsive cards.');
  await page.getByLabel('Rechercher un client ou un besoin').fill('aucun résultat fictif');await expect(page.getByRole('heading',{name:'Aucune demande pour cette recherche'})).toBeVisible();await capture(page,'search-empty-mobile','Actual search returns zero, 20 dossiers retained.');await page.getByRole('button',{name:'Effacer les filtres'}).click();await expect(page.locator('.inquiry-card')).toHaveCount(20);
  await page.route('**/api/inquiries?*',route=>route.fulfill({status:503,contentType:'application/json',body:'{"error":"service_unavailable"}'}));await page.reload();await expect(page.getByRole('main').getByRole('alert')).toContainText('Les demandes sont indisponibles');await capture(page,'list-error-mobile','Injected transport503; filter retained, no fake empty list.');await page.unrouteAll({behavior:'wait'});
  let release;const waiting=new Promise(r=>release=r);await page.route('**/api/inquiries?*',async route=>{await waiting;await route.continue();});await page.reload();await expect(page.getByRole('status')).toContainText('Chargement des demandes');await capture(page,'list-loading-mobile','Real list request held before server response.');release();await page.unrouteAll({behavior:'wait'});await expect(page.locator('.inquiry-card')).toHaveCount(20);
  await page.getByRole('link',{name:'Aller au contenu'}).focus();await tabTo(page,page.getByRole('link',{name:'Nouvelle demande',exact:true}));await expect(page.getByRole('link',{name:'Nouvelle demande',exact:true})).toBeFocused();assert.equal(await page.getByRole('link',{name:'Nouvelle demande',exact:true}).evaluate(e=>getComputedStyle(e).outlineWidth),'3px');await page.keyboard.press('Enter');
  await tabTo(page,page.getByRole('button',{name:'Enregistrer la demande',exact:true}));await page.keyboard.press('Enter');await expect(page.getByRole('main').getByRole('alert')).toContainText('Vérifiez les informations');await expect(page.getByRole('main').getByRole('alert')).toBeFocused();await expect(page.getByLabel('Nom du client',{exact:true})).toHaveAttribute('aria-describedby','error-contactName');await capture(page,'form-invalid-mobile','Actual server400 with field errors and focused summary.');
  await page.getByLabel('Nom du client',{exact:true}).focus();await page.keyboard.type('Visiteur clavier');await page.keyboard.press('Tab');await page.keyboard.press('ArrowDown');await page.keyboard.press('Tab');await page.keyboard.type('clavier@visiteur.example');await page.keyboard.press('Tab');await page.keyboard.press('Tab');await page.keyboard.type('Besoin saisi au clavier');await page.keyboard.press('Tab');await page.keyboard.type('Compte rendu fictif au clavier.');
  for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:1000});await inspect(page,'form-'+width);await capture(page,'form-filled-'+width,'Keyboard-filled manual draft; prior errors remain until next submission.');}
  const back=page.getByRole('button',{name:'Retour à la liste',exact:true});await back.focus();await page.keyboard.press('Enter');await expect(page.getByRole('dialog')).toBeVisible();const stay=page.getByRole('button',{name:'Rester sur la saisie'});await expect(stay).toBeFocused();await page.keyboard.press('Shift+Tab');await expect(page.getByRole('button',{name:'Abandonner et revenir'})).toBeFocused();await page.keyboard.press('Tab');await expect(stay).toBeFocused();await capture(page,'discard-dialog-desktop','Unsaved draft, native modal with focus loop.');await page.keyboard.press('Escape');await expect(back).toBeFocused();
  await page.getByRole('button',{name:'Enregistrer la demande',exact:true}).focus();await page.keyboard.press('Enter');await expect(page.getByRole('heading',{name:'Visiteur clavier',exact:true})).toBeVisible();await expect(page.getByRole('status').filter({hasText:'Demande enregistrée'})).toContainText('Demande enregistrée');
  for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:1000});await inspect(page,'dossier-'+width);await capture(page,'dossier-saved-'+width,'Saved real manual dossier; no proposal, reservation or outgoing message.');}
  await h.owner.query("UPDATE members SET revoked_at=now(),version=version+1 WHERE cave_id=(SELECT active_cave_id FROM app_sessions LIMIT 1) AND identity_id=(SELECT id FROM identities WHERE subject='alice')");await page.reload();await expect(page.getByRole('heading',{name:'Votre accès à cette cave a été révoqué'})).toBeVisible();await capture(page,'cave-revoked-desktop','Actual SQL revocation, protected dossier no longer displayed.');
});
test('manual form supports actual browser zoom200 and400 with all fields and actions reachable',async t=>{
  const h=await caseHarness();let browser;t.after(async()=>{if(browser)await browser.stop();await h.stop();});browser=await zoomBrowser();const page=browser.context.pages()[0];await loginPage(page,h.appOrigin);await page.goto(h.appOrigin+'/demandes?nouvelle=1');await expect(page.getByRole('button',{name:'Enregistrer la demande',exact:true})).toBeVisible();await fillManual(page);
  await page.setViewportSize({width:1280,height:1000});assert.equal(await browser.zoom(page,2),2);await expect.poll(()=>page.evaluate(()=>innerWidth)).toBe(640);await inspect(page,'zoom200');await zoomCapture(page,'form-zoom200');await browser.zoom(page,1);await page.setViewportSize({width:1280,height:1000});await browser.zoom(page,4);await expect.poll(()=>page.evaluate(()=>innerWidth)).toBe(320);await inspect(page,'zoom400');await zoomCapture(page,'form-zoom400');await browser.zoom(page,1);
});

test('manual save waiting and real server failure preserve the draft until the exact command succeeds',async t=>{
  const h=await caseHarness();let browser;t.after(async()=>{if(browser)await browser.close();await h.stop();});browser=await chromium.launch();const page=await browser.newPage({viewport:{width:390,height:844}});await loginPage(page,h.appOrigin);await page.goto(h.appOrigin+'/demandes?nouvelle=1');await fillManual(page);
  await h.owner.query("CREATE FUNCTION ux_manual_reject() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'synthetic journal failure'; END $$; CREATE TRIGGER ux_manual_reject BEFORE INSERT ON inquiry_commands FOR EACH ROW EXECUTE FUNCTION ux_manual_reject()");
  let release;const waiting=new Promise(r=>release=r);await page.route('**/api/inquiries/manual',async route=>{await waiting;await route.continue();});await page.getByRole('button',{name:'Enregistrer la demande',exact:true}).click();await expect(page.getByRole('status')).toContainText('Enregistrement en cours');await expect(page.getByLabel('Nom du client',{exact:true})).toBeDisabled();await capture(page,'save-pending-mobile','Real command held in browser transport; no server success yet.');release();await page.unrouteAll({behavior:'wait'});
  await expect(page.getByRole('main').getByRole('alert')).toContainText('L’enregistrement n’est pas confirmé');await expect(page.getByLabel('Nom du client',{exact:true})).toHaveValue('Camille Fictive');await expect(page.getByRole('button',{name:'Vérifier l’enregistrement',exact:true})).toBeVisible();assert.equal((await h.pool.query('SELECT count(*)::int n FROM inquiries')).rows[0].n,0);await inspect(page,'save-failed-mobile');await capture(page,'save-failed-mobile','Real PostgreSQL journal failure, transaction rolled back; same command retained for verification.');
  await h.owner.query("UPDATE members SET role='reader' WHERE cave_id=(SELECT active_cave_id FROM app_sessions LIMIT 1) AND identity_id=(SELECT id FROM identities WHERE subject='alice')");await page.getByRole('button',{name:'Vérifier l’enregistrement',exact:true}).click();await expect(page.getByRole('main').getByRole('alert')).toContainText('Votre rôle ne permet pas cette action.');await expect(page.getByLabel('Nom du client',{exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'Vérifier l’enregistrement',exact:true})).toBeVisible();await capture(page,'save-verification-forbidden-mobile','Real403 after reader demotion; uncertain command retained unchanged.');
  await h.owner.query("UPDATE members SET role='admin' WHERE cave_id=(SELECT active_cave_id FROM app_sessions LIMIT 1) AND identity_id=(SELECT id FROM identities WHERE subject='alice')");await h.owner.query('DROP TRIGGER ux_manual_reject ON inquiry_commands');await page.getByRole('button',{name:'Vérifier l’enregistrement',exact:true}).click();await expect(page.getByRole('heading',{name:'Camille Fictive',exact:true})).toBeVisible();assert.equal((await h.pool.query('SELECT count(*)::int n FROM inquiries')).rows[0].n,1);
});
