import test,{after} from 'node:test';
import assert from 'node:assert/strict';
import { mkdir,readFile,writeFile } from 'node:fs/promises';
import { randomBytes,createHash } from 'node:crypto';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { chromium,expect } from '@playwright/test';
import { caseHarness } from '../helpers/case-harness.mjs';
import { HttpBrowser } from '../helpers/identity-harness.mjs';
import { loginPage } from '../helpers/browser-actions.mjs';
import { configureForm,formDefinition,fillPublic } from '../helpers/public-form-harness.mjs';
import { manualRead } from '../helpers/manual-harness.mjs';
import { zoomBrowser } from '../helpers/ux-browser.mjs';
const root=fileURLToPath(new URL('../../../',import.meta.url)),directory=join(root,'.local/ux/EA-12',`${Date.now()}-${randomBytes(3).toString('hex')}`);await mkdir(directory,{recursive:true});
const evidence={note:'Real Chromium/API/PostgreSQL, synthetic data, injected transport failures labelled. No external account or mail delivery.',captures:[],measurements:[]};
async function capture(page,name,serverState,bytes,extra={}){const path=join(directory,name+'.png');if(bytes)await writeFile(path,bytes);else await page.screenshot({path,fullPage:true,animations:'disabled'});evidence.captures.push({name,path,viewport:page.viewportSize(),serverState,sha256:createHash('sha256').update(await readFile(path)).digest('hex'),...extra});}
after(async()=>{await writeFile(join(directory,'manifest.json'),JSON.stringify(evidence,null,2)+'\n');await writeFile(join(root,'.local/ux/EA-12/latest.json'),JSON.stringify({directory,verdict:'see_test_log'})+'\n');console.log('Public form UX captures: '+evidence.captures.length);});
async function inspect(page,label){const value=await page.evaluate(()=>{
 const visible=e=>{const r=e.getBoundingClientRect();return r.width&&r.height&&!e.closest('[aria-hidden="true"]');},bg=e=>{for(let p=e;p;p=p.parentElement){const c=getComputedStyle(p).backgroundColor;if(c!=='rgba(0, 0, 0, 0)'&&c!=='transparent')return c;}return'rgb(255,255,255)';},lum=c=>c.match(/[\d.]+/g).slice(0,3).map(Number).map(n=>n/255).map(n=>n<=.04045?n/12.92:((n+.055)/1.055)**2.4).reduce((s,n,i)=>s+n*[.2126,.7152,.0722][i],0),ratio=(a,b)=>(Math.max(lum(a),lum(b))+.05)/(Math.min(lum(a),lum(b))+.05);
 return{width:document.documentElement.clientWidth,scrollWidth:document.documentElement.scrollWidth,targets:[...document.querySelectorAll('button,input,textarea,select,a.button,a.error-link')].filter(visible).map(e=>{const r=e.getBoundingClientRect();return{width:r.width,height:r.height,left:r.left,right:r.right};}),contrast:Math.min(...[...document.querySelectorAll('h1,h2,h3,p,label,dt,dd,strong,.button')].filter(visible).map(e=>ratio(getComputedStyle(e).color,bg(e)))),borders:[...document.querySelectorAll('input,textarea,select')].filter(visible).map(e=>ratio(getComputedStyle(e).borderTopColor,bg(e)))};
 });assert.ok(value.scrollWidth<=value.width+1,label+': horizontal overflow');for(const r of value.targets){assert.ok(r.width>=43.9&&r.height>=43.9,label+': target44');assert.ok(r.left>=-1&&r.right<=value.width+1,label+': offscreen');}assert.ok(value.contrast>=4.5,label+': text contrast');for(const c of value.borders)assert.ok(c>=3,label+': input contrast');evidence.measurements.push({label,...value});}
async function tabTo(page,target){for(let n=0;n<40;n++){if(await target.evaluate(e=>e===document.activeElement))return;await page.keyboard.press('Tab');}assert.fail('Keyboard target not reached');}
async function setup(t,zoom=false,definition={}){const h=await caseHarness();let browser;t.after(async()=>{if(browser){if(zoom)await browser.stop();else await browser.close();}await h.stop();});const staff=new HttpBrowser(h.appOrigin);await staff.login('alice');const form=await configureForm(staff,{definition:formDefinition(definition)});assert.equal(form.status,200);browser=zoom?await zoomBrowser():await chromium.launch();const page=zoom?browser.context.pages()[0]:await browser.newPage({viewport:{width:1440,height:1000}});return{...h,staff,form:form.body,browser,page};}
async function zoomCapture(page,name){const cdp=await page.context().newCDPSession(page);try{await page.evaluate(()=>scrollTo(0,0));for(let n=0;n<24;n++){await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const m=await page.evaluate(()=>({scrollY,innerWidth,innerHeight,height:document.documentElement.scrollHeight,devicePixelRatio}));const result=await cdp.send('Page.captureScreenshot',{format:'png',fromSurface:true,captureBeyondViewport:false});await capture(page,`${name}-${n+1}`,'Actual browser zoom; overlapping visible viewport, full vertical coverage.',Buffer.from(result.data,'base64'),m);if(m.scrollY+m.innerHeight>=m.height-1)return;await page.evaluate(()=>scrollBy(0,Math.floor(innerHeight*.9)));}assert.fail('Zoom traversal exhausted');}finally{await cdp.detach();await page.evaluate(()=>scrollTo(0,0));}}
test('public form exposes responsive states, linked validation and keyboard submission with honest receipt',async t=>{
 const h=await setup(t),page=h.page;let release;const held=new Promise(r=>release=r);await page.route('**/api/public/forms/*',async route=>{await held;await route.continue();});await page.goto(h.form.url);await expect(page.getByRole('status')).toContainText('Chargement');await capture(page,'loading-desktop','Real GET held before response.');release();await page.unrouteAll({behavior:'wait'});await expect(page.getByRole('button',{name:'Envoyer ma demande'})).toBeEnabled();
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:1000});await inspect(page,'form-'+width);await capture(page,'form-'+width,'Active configured cave, no visitor account, empty form.');}
 await page.getByRole('link',{name:'Aller au contenu'}).focus();await tabTo(page,page.getByLabel('Votre nom',{exact:true}));assert.equal(await page.getByLabel('Votre nom',{exact:true}).evaluate(e=>getComputedStyle(e).outlineWidth),'3px');await page.keyboard.type('Visiteur clavier');await page.keyboard.press('Tab');await page.keyboard.type('clavier@visiteur.example');await page.keyboard.press('Tab');await page.keyboard.press('Tab');await page.keyboard.type('Demande de visite au clavier.');await tabTo(page,page.getByRole('button',{name:'Envoyer ma demande'}));
 await page.getByLabel('Adresse e-mail',{exact:true}).fill('');await page.getByRole('button',{name:'Envoyer ma demande'}).click();await expect(page.getByRole('main').getByRole('alert')).toContainText('Vérifiez');await expect(page.getByRole('main').getByRole('alert')).toBeFocused();await expect(page.getByLabel('Adresse e-mail',{exact:true})).toHaveAttribute('aria-describedby','help-contactEmail error-contactEmail');await page.setViewportSize({width:390,height:844});await inspect(page,'invalid-mobile');await capture(page,'invalid-mobile','Server400, missing response channel, other fields preserved, focused linked errors.');const errorJump=page.getByRole('main').getByRole('alert').getByRole('link');await expect(errorJump).toHaveCount(1);await errorJump.focus();await page.keyboard.press('Enter');await expect(page.getByLabel('Adresse e-mail',{exact:true})).toBeFocused();await capture(page,'error-link-focus-mobile','Keyboard activation of summary link focuses the corresponding response field without clearing the draft.');
 await page.getByLabel('Adresse e-mail',{exact:true}).fill('clavier@visiteur.example');await page.getByRole('button',{name:'Envoyer ma demande'}).focus();await page.keyboard.press('Enter');await expect(page.getByRole('heading',{name:'Demande reçue',exact:true})).toBeFocused();for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:1000});await inspect(page,'receipt-'+width);await capture(page,'receipt-'+width,'Committed real inquiry, no email sent and no booking.');}
 const id=(await manualRead(h.staff)).body.items[0].id;const staffPage=await h.browser.newPage();await loginPage(staffPage,h.appOrigin);await staffPage.goto(h.appOrigin+'/demandes?id='+id);await expect(staffPage.getByText('Formulaire du site',{exact:true})).toBeVisible();for(const width of [390,1440]){await staffPage.setViewportSize({width,height:1000});await inspect(staffPage,'staff-dossier-'+width);await capture(staffPage,'staff-dossier-'+width,'Same persisted visitor source, no staff actor invented, response channel visible.');}
});
test('public pending, failure, unavailable, expiry and SQL rate limits preserve factual states',async t=>{
 const h=await setup(t,false,{attemptLimitPerMinute:3}),page=h.page;await page.setViewportSize({width:390,height:844});await page.goto(h.form.url);await fillPublic(page);let release;const held=new Promise(r=>release=r);await page.route('**/api/public/forms/*',async route=>{if(route.request().method()==='POST'){await held;await route.abort('failed');}else await route.continue();});await page.getByRole('button',{name:'Envoyer ma demande'}).click();await expect(page.getByRole('status')).toContainText('Envoi en cours');await capture(page,'pending-mobile','POST held before API; no success announced.');release();await expect(page.getByRole('main').getByRole('alert')).toContainText('n’est pas confirmée');await page.unrouteAll({behavior:'wait'});await inspect(page,'uncertain-mobile');await capture(page,'uncertain-mobile','Injected failed transport; identical command persisted, fields locked.');
 await configureForm(h.staff,{expectedVersion:1,enabled:false});await page.getByRole('button',{name:'Vérifier la réception'}).click();await expect(page.getByRole('main').getByRole('alert')).toContainText('indisponible');await capture(page,'uncertain-disabled-mobile','Real404 on verification after admin disables form; original command retained.');const other=await h.browser.newPage({viewport:{width:390,height:844}});await other.goto(h.form.url);await expect(other.getByRole('main').getByRole('alert')).toContainText('indisponible');await capture(other,'unavailable-mobile','Fresh visitor, actual disabled form404, no usable intake.');await other.close();
 await configureForm(h.staff,{expectedVersion:2,enabled:true,definition:formDefinition({attemptLimitPerMinute:3})});await page.getByRole('button',{name:'Vérifier la réception'}).click();await expect(page.getByRole('button',{name:'Actualiser en conservant ma saisie'})).toBeVisible();await capture(page,'version-changed-mobile','Server proves no matching intake and configuration version changed; draft editable.');await page.getByRole('button',{name:'Actualiser en conservant ma saisie'}).click();await expect(page.getByRole('button',{name:'Envoyer ma demande'})).toBeEnabled();await h.owner.query("UPDATE public_form_challenges SET issued_at=now()-interval '1 hour',expires_at=now()-interval '1 second'");await page.getByRole('button',{name:'Envoyer ma demande'}).click();await expect(page.getByRole('button',{name:'Actualiser en conservant ma saisie'})).toBeVisible();await capture(page,'expired-mobile','Actual expired challenge410 and safe refresh preserving draft.');await page.getByRole('button',{name:'Actualiser en conservant ma saisie'}).click();await expect(page.getByRole('button',{name:'Envoyer ma demande'})).toBeEnabled();await h.owner.query("UPDATE public_form_challenges SET issued_at=now()-interval '1 hour',expires_at=now()-interval '1 second'");const cleanupVisitor=await h.browser.newPage();await cleanupVisitor.goto(h.form.url);await expect(cleanupVisitor.getByRole('button',{name:'Envoyer ma demande'})).toBeEnabled();await cleanupVisitor.close();await page.getByRole('button',{name:'Envoyer ma demande'}).click();await expect(page.getByRole('button',{name:'Actualiser en conservant ma saisie'})).toBeVisible();await expect(page.getByLabel('Votre nom',{exact:true})).toBeEnabled();await capture(page,'cleaned-challenge-mobile','Expired challenge actually cleaned by a second visitor; server proves absence and preserves editable draft.');await page.getByRole('button',{name:'Actualiser en conservant ma saisie'}).click();await page.getByRole('button',{name:'Envoyer ma demande'}).click();await expect(page.getByRole('main').getByRole('alert')).toContainText('trop de tentatives');await capture(page,'rate-limited-mobile','Actual SQL minute quota429; Retry-After visible and pending preserved.');await expect(page.getByLabel('Votre nom',{exact:true})).toHaveValue('Camille Visiteur');assert.equal((await h.pool.query('SELECT count(*)::int n FROM inquiries')).rows[0].n,0);
});
test('public form supports actual browser zoom200 and400 with reachable fields and submission',async t=>{
 const h=await setup(t,true),page=h.page;await page.goto(h.form.url);await fillPublic(page);await page.setViewportSize({width:1280,height:1000});for(const factor of [2,4]){assert.ok(Math.abs(await h.browser.zoom(page,factor)-factor)<1e-12);await expect.poll(()=>page.evaluate(()=>innerWidth)).toBe(1280/factor);await inspect(page,'zoom'+factor*100);await zoomCapture(page,'zoom'+factor*100);await h.browser.zoom(page,1);}
});
