import { createServer } from 'node:http';
import { randomBytes,createHash } from 'node:crypto';
import { generateKeyPair,exportJWK,SignJWT } from 'jose';
const login='https://login.microsoftonline.com';
export const fixtureMicrosoftClientId='eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee';
export const fixtureMicrosoftAccounts={
 a:{tenantId:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',accountId:'aaaaaaaa-0000-4000-8000-000000000001',displayName:'Compte Microsoft synthétique A',username:'compte-a@organisation-fictive.example'},
 b:{tenantId:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',accountId:'bbbbbbbb-0000-4000-8000-000000000002',displayName:'Compte Microsoft synthétique B',username:'compte-b@organisation-fictive.example'},
};
const opaque=()=>randomBytes(32).toString('base64url');
export async function microsoftFixture(port,appOrigin){
 const {publicKey,privateKey}=await generateKeyPair('RS256'),jwk={...await exportJWK(publicKey),kid:'synthetic-microsoft-key',alg:'RS256',use:'sig'},clientSecret=opaque(),requests=[],authorizations=new Map(),codes=new Map(),tokens=new Map(),refreshes=new Map();
 const controls={idTokenMode:'valid',graphMode:'valid',refreshMode:'valid',missing:new Set(),revoked:new Set(),beforeGraph:null,expiresIn:3600};
 const redirectUri=appOrigin+'/api/connections/microsoft/callback';
 function approve(url,account='a',failure=null){const u=new URL(url),p=u.searchParams;if(p.get('client_id')!==fixtureMicrosoftClientId||p.get('redirect_uri')!==redirectUri||p.get('code_challenge_method')!=='S256')throw new Error('Invalid synthetic authorization request');const result=new URL(redirectUri);result.searchParams.set('state',p.get('state'));if(failure){result.searchParams.set('error',failure);if(failure==='admin_consent_required')result.searchParams.set('error_codes','[90094]');}else{const code=opaque();codes.set(code,{account,challenge:p.get('code_challenge'),nonce:p.get('nonce'),scope:p.get('scope')});result.searchParams.set('code',code);}return result.href;}
 async function token(grant){const person=fixtureMicrosoftAccounts[grant.account],accessToken=opaque(),refreshToken=opaque();tokens.set(accessToken,grant.account);refreshes.set(refreshToken,grant);const tid=controls.idTokenMode==='personal'?'9188040d-6c67-4c5b-b112-36a304b66dad':person.tenantId;
  const jwt=await new SignJWT({tid,oid:person.accountId,sub:'synthetic-'+person.accountId,ver:'2.0',name:person.displayName,preferred_username:person.username,nonce:controls.idTokenMode==='nonce'?opaque():grant.nonce}).setProtectedHeader({alg:'RS256',kid:jwk.kid}).setIssuer(controls.idTokenMode==='issuer'?login+'/cccccccc-cccc-4ccc-8ccc-cccccccccccc/v2.0':login+'/'+tid+'/v2.0').setAudience(controls.idTokenMode==='audience'?'dddddddd-dddd-4ddd-8ddd-dddddddddddd':fixtureMicrosoftClientId).setIssuedAt().setExpirationTime(controls.idTokenMode==='expired'?Math.floor(Date.now()/1000)-60:'1h').sign(privateKey);
  return{token_type:'Bearer',scope:grant.scope,expires_in:controls.expiresIn,ext_expires_in:controls.expiresIn,access_token:accessToken,refresh_token:refreshToken,id_token:controls.idTokenMode==='signature'?jwt.slice(0,-20)+'x'.repeat(20):jwt,client_info:Buffer.from(JSON.stringify({uid:person.accountId,utid:tid})).toString('base64url')};
 }
 const server=createServer((req,res)=>{void (async()=>{
  const u=new URL(req.url,'http://127.0.0.1:'+port),path=u.pathname;requests.push({method:req.method,path});const json=(status,body,headers={})=>{res.writeHead(status,{'content-type':'application/json',...headers});res.end(JSON.stringify(body));};
  if(path==='/identity/common/discovery/instance'){json(200,{tenant_discovery_endpoint:login+'/organizations/v2.0/.well-known/openid-configuration',metadata:[{preferred_network:'login.microsoftonline.com',preferred_cache:'login.microsoftonline.com',aliases:['login.microsoftonline.com','login.windows.net','login.microsoft.com','sts.windows.net']}]});return;}
  if(path.endsWith('/.well-known/openid-configuration')){const tenant=path.split('/')[2];json(200,{authorization_endpoint:login+'/'+tenant+'/oauth2/v2.0/authorize',token_endpoint:login+'/'+tenant+'/oauth2/v2.0/token',issuer:login+'/{tenantid}/v2.0',jwks_uri:login+'/'+tenant+'/discovery/v2.0/keys',end_session_endpoint:login+'/'+tenant+'/oauth2/v2.0/logout',response_types_supported:['code'],subject_types_supported:['pairwise'],id_token_signing_alg_values_supported:['RS256']});return;}
  if(path.endsWith('/discovery/v2.0/keys')){json(200,{keys:[{...jwk,issuer:login+'/{tenantid}/v2.0'}]});return;}
  if(path.endsWith('/oauth2/v2.0/authorize')){const request=opaque();authorizations.set(request,u.href);res.writeHead(200,{'content-type':'text/html; charset=utf-8','cache-control':'no-store'});res.end(`<!doctype html><html lang="fr"><title>Microsoft synthétique</title><h1>Fournisseur Microsoft synthétique</h1><p>Aucun compte réel. Choisissez une organisation fictive.</p><form method="post" action="/fixture/choice"><input type="hidden" name="request" value="${request}"><button name="choice" value="a">Compte synthétique A</button><button name="choice" value="b">Compte synthétique B</button><button name="choice" value="denied">Refuser le consentement</button><button name="choice" value="admin">Consentement administrateur requis</button></form></html>`);return;}
  if(path==='/fixture/choice'&&req.method==='POST'){let body='';for await(const chunk of req){body+=chunk;if(body.length>16384)throw new Error('Oversized fixture choice');}const p=new URLSearchParams(body),url=authorizations.get(p.get('request'));authorizations.delete(p.get('request'));if(!url){json(400,{error:'invalid_request'});return;}const choice=p.get('choice'),failure=choice==='denied'?'access_denied':choice==='admin'?'admin_consent_required':null;res.writeHead(303,{location:approve(url,choice==='b'?'b':'a',failure)}).end();return;}
  if(path.endsWith('/oauth2/v2.0/token')&&req.method==='POST'){let body='';for await(const chunk of req){body+=chunk;if(body.length>16384)throw new Error('Oversized fixture token request');}const p=new URLSearchParams(body);if(p.get('client_id')!==fixtureMicrosoftClientId||p.get('client_secret')!==clientSecret){json(401,{error:'invalid_client'});return;}
   let grant;if(p.get('grant_type')==='authorization_code'){grant=codes.get(p.get('code'));codes.delete(p.get('code'));if(!grant||p.get('redirect_uri')!==redirectUri||createHash('sha256').update(p.get('code_verifier')??'').digest('base64url')!==grant.challenge){json(400,{error:'invalid_grant'});return;}}
   else if(p.get('grant_type')==='refresh_token'){grant=refreshes.get(p.get('refresh_token'));if(controls.refreshMode==='admin'){json(400,{error:'consent_required',error_codes:[90094],error_description:'synthetic private diagnostic'});return;}if(!grant||controls.refreshMode!=='valid'||controls.revoked.has(grant.account)){json(400,{error:'invalid_grant',suberror:'interaction_required'});return;}}
   else{json(400,{error:'unsupported_grant_type'});return;}json(200,await token(grant));return;
  }
  if(path.startsWith('/graph/v1.0/')){const account=tokens.get((req.headers.authorization??'').replace(/^Bearer /,''));if(!account||controls.revoked.has(account)){json(401,{error:{code:'InvalidAuthenticationToken'}});return;}if(controls.beforeGraph)await controls.beforeGraph({account,path});if(controls.graphMode==='rate'){json(429,{error:{code:'TooManyRequests'}},{'retry-after':'7'});return;}if(controls.graphMode==='unavailable'){json(503,{error:{code:'Unavailable'}});return;}const person=fixtureMicrosoftAccounts[account];
   if(path==='/graph/v1.0/me'){json(200,{id:controls.graphMode==='identity'?fixtureMicrosoftAccounts[account==='a'?'b':'a'].accountId:person.accountId,displayName:person.displayName,userPrincipalName:person.username});return;}
   if(path==='/graph/v1.0/me/mailFolders/inbox'){json(controls.missing.has('mailbox')?403:200,controls.missing.has('mailbox')?{error:{code:'ErrorAccessDenied'}}:{id:'synthetic-inbox-'+person.accountId,displayName:'Boîte de réception fictive'});return;}
   if(path==='/graph/v1.0/me/calendar'){json(controls.missing.has('calendar')?403:200,controls.missing.has('calendar')?{error:{code:'ErrorAccessDenied'}}:{id:'synthetic-calendar-'+person.accountId,name:'Calendrier principal fictif '+account.toUpperCase(),canEdit:true});return;}
  }
  json(404,{error:'not_found'});
 })().catch(()=>{if(!res.headersSent)res.writeHead(500,{'content-type':'application/json'});res.end('{"error":"synthetic_fixture_error"}');});});
 await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(port,'127.0.0.1',resolve);});
 return{settings:{clientId:fixtureMicrosoftClientId,clientSecret,encryptionKey:randomBytes(32).toString('hex'),keyVersion:'v1',fixtureOrigin:'http://127.0.0.1:'+port},controls,requests,approve,stop:async()=>{server.closeAllConnections();await new Promise(r=>server.close(r));}};
}
