import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { identityHarness,HttpBrowser } from './identity-harness.mjs';
export const manualInput=(overrides={})=>({contactName:'Camille Fictive',contactEmail:'camille@visiteur.example',contactPhone:null,subject:'Dégustation après appel fictif',note:'Compte rendu fictif : souhaite découvrir la cave.',origin:'phone',requestedDate:null,participants:null,budgetMinor:null,budgetBasis:null,...overrides});
export async function manualHarness(t){const h=await identityHarness();t.after(()=>h.stop());const browser=new HttpBrowser(h.appOrigin);await browser.login('alice');return{...h,browser};}
export async function manualCreate(browser,input=manualInput(),key=randomUUID(),headers={}){const r=await browser.command('/api/inquiries/manual',input,{'idempotency-key':key,...headers});return{status:r.status,body:await r.json()};}
export async function manualRead(browser,path=''){const s=await browser.session(),r=await browser.request('/api/inquiries'+path,{headers:{'x-encave-cave':s.body.activeCave.id}});return{status:r.status,body:await r.json()};}
export async function seedQueue(browser,count=20){const ids=[];for(let n=0;n<count;n++){const r=await manualCreate(browser,manualInput({contactName:`Visiteur fictif ${String(n+1).padStart(2,'0')}`,subject:`Besoin synthétique ${n+1}`,requestedDate:n%3===0?`2026-10-${String(n%28+1).padStart(2,'0')}`:null,participants:n%2?null:n+2}));assert.equal(r.status,201);ids.push(r.body.id);}return ids;}
export async function fillManual(page,overrides={}){const d=manualInput(overrides);await page.getByLabel('Nom du client',{exact:true}).fill(d.contactName);await page.getByLabel('Adresse e-mail',{exact:true}).fill(d.contactEmail??'');await page.getByLabel('Téléphone',{exact:true}).fill(d.contactPhone??'');await page.getByLabel('Besoin du client',{exact:true}).fill(d.subject);await page.getByLabel('Compte rendu de l’échange',{exact:true}).fill(d.note);await page.getByLabel('Origine de la saisie',{exact:true}).selectOption(d.origin);}
