import { randomUUID,createHash } from 'node:crypto';
import type { Pool,PoolClient } from 'pg';
import { AccessError,inCave,checkCsrf,validId,transaction,lockCave,type CommandContext } from '@encave/tenancy';
import { beginConnectionSchema,connectionVersionSchema,selectConnectionResourcesSchema,ConnectorError,type ProviderResource,type ConnectorOperation } from '@encave/contracts';
import { MicrosoftAdapter,CredentialCipher,validateMicrosoftSettings,providerFailure,type MicrosoftSettings,type MicrosoftCredentials,type MicrosoftDiscovery } from '@encave/connectors';
import { opaqueToken,tokenHash,validToken } from './identity-security.ts';
type Row=Record<string,any>;
type Flow={state:string;verifier:string;nonce:string};
const sha=(v:unknown)=>createHash('sha256').update(JSON.stringify(v)).digest('hex');
const errorCode=(e:unknown)=>e instanceof ConnectorError?e.code:'provider_unavailable';
export class ConnectionStore {
 readonly pool:Pool;readonly appOrigin:string;readonly environment:string;readonly settings:MicrosoftSettings|undefined;readonly cipher:CredentialCipher|undefined;
 constructor(pool:Pool,appOrigin:string,environment:string,settings?:MicrosoftSettings){this.pool=pool;this.appOrigin=appOrigin;this.environment=environment;this.settings=settings;if(settings){validateMicrosoftSettings(settings,environment);this.cipher=new CredentialCipher(settings.encryptionKey,settings.keyVersion);}}
 private required(){if(!this.settings||!this.cipher)throw new AccessError(503,'microsoft_not_configured');return{settings:this.settings,cipher:this.cipher};}
 private async admin<T>(context:CommandContext,fn:(db:PoolClient,cave:string,actor:string,sessionHash:string)=>Promise<T>,csrf=true){return inCave(this.pool,context,'read',async(db,s,m)=>{if(csrf)checkCsrf(s,context.csrf);if(m.role!=='admin')throw new AccessError(403,'role_forbidden');return fn(db,s.active_cave_id,s.identity_id,s.token_hash);});}
 private async row(db:PoolClient,cave:string,id:unknown){if(!validId(id))throw new AccessError(404,'connection_not_found');const row=(await db.query('SELECT * FROM provider_connections WHERE cave_id=$1 AND id=$2',[cave,id])).rows[0];if(!row)throw new AccessError(404,'connection_not_found');return row as Row;}
 private version(row:Row,expected:unknown){if(row.version!==expected||row.version>=100000||row.authorization_version>=100000)throw new AccessError(409,'connection_changed');}
 private async command(db:PoolClient,cave:string,actor:string,key:string,hash:string){const old=(await db.query('SELECT payload_hash,result FROM provider_connection_commands WHERE cave_id=$1 AND actor_id=$2 AND request_key=$3',[cave,actor,key])).rows[0];if(old&&old.payload_hash!==hash)throw new AccessError(409,'idempotency_conflict');return old?.result;}
 private async journal(db:PoolClient,cave:string,actor:string,id:string,key:string,kind:string,hash:string,result:unknown){await db.query('INSERT INTO provider_connection_commands(cave_id,actor_id,connection_id,request_key,kind,payload_hash,result) VALUES($1,$2,$3,$4,$5,$6,$7)',[cave,actor,id,key,kind,hash,result]);}
 private async event(db:PoolClient,cave:string,actor:string,row:Row,kind:string){await db.query('INSERT INTO provider_connection_events(cave_id,connection_id,id,actor_id,version,authorization_version,kind,status,diagnostic) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[cave,row.id,randomUUID(),actor,row.version,row.authorization_version,kind,row.status,row.last_error??null]);}
 private scope(cave:string,id:string,purpose:string){return{caveId:cave,connectionId:id,purpose};}
 private async guard(context:CommandContext,id:string,authorizationVersion:number){await this.admin(context,async(db,cave)=>{const row=await this.row(db,cave,id);if(row.status==='revoked'||row.authorization_version!==authorizationVersion)throw new AccessError(409,'connection_changed');},false);}
 private adapter(context:CommandContext,id:string,authorizationVersion:number){return new MicrosoftAdapter(this.required().settings,this.appOrigin,this.environment,()=>this.guard(context,id,authorizationVersion));}
 private async resources(db:PoolClient,cave:string,id:string):Promise<ProviderResource[]>{return(await db.query('SELECT kind,id,name,owner_id AS "ownerId",writable FROM provider_resources WHERE cave_id=$1 AND connection_id=$2 ORDER BY kind,id',[cave,id])).rows;}
 private dto(row:Row,resources:ProviderResource[]){const expired=row.expires_at&&new Date(row.expires_at).getTime()<=Date.now(),status=expired&&!['revoked','consent_denied','admin_consent_required'].includes(row.status)?'reconnect_required':row.status;
  const adapter=this.settings?new MicrosoftAdapter(this.settings,this.appOrigin,this.environment):null;return{id:row.id,caveId:row.cave_id,label:row.label,provider:row.provider,profile:row.profile,synthetic:row.synthetic,version:row.version,authorizationVersion:row.authorization_version,status,identity:row.provider_account_id?{tenantId:row.provider_tenant_id,accountId:row.provider_account_id,displayName:row.display_name,username:row.username}:null,mailboxId:row.mailbox_id,calendarId:row.calendar_id,resources,capabilities:adapter?.capabilities(status==='active',resources)??[],expiresAt:row.expires_at,lastCheckedAt:row.last_checked_at,lastSuccessAt:row.last_success_at,lastSynchronizationAt:null,lastError:row.last_error,missingResources:row.missing_resources,canActivate:Boolean(row.synthetic&&this.settings?.fixtureOrigin&&status==='unqualified'&&!row.last_error&&(row.mailbox_id||row.calendar_id))};
 }
 async list(context:CommandContext){return inCave(this.pool,context,'read',async(db,s)=>{const rows=(await db.query('SELECT * FROM provider_connections WHERE cave_id=$1 ORDER BY created_at,id LIMIT 50',[s.active_cave_id])).rows;const items=[];for(const row of rows)items.push(this.dto(row,await this.resources(db,s.active_cave_id,row.id)));return{caveId:s.active_cave_id,configured:Boolean(this.settings),synthetic:Boolean(this.settings?.fixtureOrigin),items};});}
 async begin(context:CommandContext,input:unknown,key:unknown){
  const configured=this.required();if(!validId(key))throw new AccessError(400,'invalid_idempotency_key');const parsed=beginConnectionSchema.safeParse(input);if(!parsed.success)throw new AccessError(400,'invalid_connection');const p=parsed.data,hash=sha(['begin',p]);
  const attempt=await this.admin(context,async(db,cave,actor,sessionHash)=>{
   const replay=await this.command(db,cave,actor,key,hash);if(replay){const old=(await db.query('SELECT a.* FROM provider_oauth_attempts a WHERE cave_id=$1 AND connection_id=$2 AND id=$3',[cave,replay.id,replay.attemptId])).rows[0];if(!old||old.actor_id!==actor)throw new AccessError(409,'oauth_invalid');
    if(old.session_hash!==sessionHash&&['pending','consumed'].includes(old.status)){
     const current=await this.row(db,cave,old.connection_id);
     await db.query("UPDATE provider_oauth_attempts SET status='cancelled',encrypted_flow=NULL WHERE cave_id=$1 AND connection_id=$2 AND id=$3",[cave,old.connection_id,old.id]);
     if(current.status==='oauth_pending'&&current.authorization_version===old.authorization_version){
      await db.query('DELETE FROM provider_credentials WHERE cave_id=$1 AND connection_id=$2',[cave,current.id]);
      const recovered=(await db.query("UPDATE provider_connections SET version=version+1,authorization_version=authorization_version+1,status='reconnect_required',last_error='interaction_required',updated_at=now() WHERE cave_id=$1 AND id=$2 RETURNING *",[cave,current.id])).rows[0];
      await this.event(db,cave,actor,recovered,'oauth_session_recovered');
     }
     return{...old,status:'cancelled',encrypted_flow:null};
    }
    return old;}
   let row:Row;if(p.connectionId===null){if(p.expectedVersion!==0)throw new AccessError(409,'connection_changed');if((await db.query('SELECT count(*)::int n FROM provider_connections WHERE cave_id=$1',[cave])).rows[0].n>=50)throw new AccessError(409,'connection_limit');row=(await db.query("INSERT INTO provider_connections(cave_id,id,provider,synthetic,label,status,created_by,expires_at) VALUES($1,$2,'microsoft365',$3,$4,'oauth_pending',$5,now()+interval '10 minutes') RETURNING *",[cave,randomUUID(),Boolean(this.settings?.fixtureOrigin),p.label,actor])).rows[0];}
   else{row=await this.row(db,cave,p.connectionId);this.version(row,p.expectedVersion);await db.query('DELETE FROM provider_credentials WHERE cave_id=$1 AND connection_id=$2',[cave,row.id]);await db.query('DELETE FROM provider_routing_claims WHERE cave_id=$1 AND connection_id=$2',[cave,row.id]);await db.query("UPDATE provider_oauth_attempts SET status='cancelled',encrypted_flow=NULL WHERE cave_id=$1 AND connection_id=$2 AND status IN ('pending','consumed')",[cave,row.id]);row=(await db.query("UPDATE provider_connections SET version=version+1,authorization_version=authorization_version+1,status='oauth_pending',label=$3,last_error=NULL,expires_at=now()+interval '10 minutes',updated_at=now() WHERE cave_id=$1 AND id=$2 RETURNING *",[cave,row.id,p.label])).rows[0];}
   const id=randomUUID(),flow={state:opaqueToken(),verifier:opaqueToken(),nonce:opaqueToken()},encrypted=configured.cipher.seal(flow,this.scope(cave,row.id,'oauth:'+id));const a=(await db.query("INSERT INTO provider_oauth_attempts(cave_id,connection_id,id,state_hash,actor_id,session_hash,authorization_version,encrypted_flow,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,now()+interval '10 minutes') RETURNING *",[cave,row.id,id,tokenHash(flow.state),actor,sessionHash,row.authorization_version,encrypted])).rows[0];await this.journal(db,cave,actor,row.id,key,'begin',hash,{id:row.id,attemptId:id});await this.event(db,cave,actor,row,'oauth_started');return a;
  });
  if(attempt.status==='succeeded')return{id:attempt.connection_id,alreadyCompleted:true};if(attempt.status!=='pending'||new Date(attempt.expires_at).getTime()<=Date.now())return{id:attempt.connection_id,requiresReconnect:true};const flow=configured.cipher.open<Flow>(attempt.encrypted_flow,this.scope(attempt.cave_id,attempt.connection_id,'oauth:'+attempt.id));const url=await this.adapter(context,attempt.connection_id,attempt.authorization_version).authorization(flow);return{id:attempt.connection_id,url};
 }
 async callback(token:string,url:URL){
  this.required();const state=url.searchParams.get('state');if(!validToken(state)||url.searchParams.getAll('state').length!==1||url.searchParams.getAll('code').length>1||url.searchParams.getAll('error').length>1)throw new AccessError(400,'oauth_invalid');
  const found=(await this.pool.query('SELECT cave_id,connection_id FROM provider_oauth_attempts WHERE state_hash=$1',[tokenHash(state)])).rows[0];if(!found)throw new AccessError(400,'oauth_invalid');const context={token,csrf:'',expectedCave:found.cave_id};
  const attempt=await this.admin(context,async(db,cave,actor,sessionHash)=>{const a=(await db.query("SELECT * FROM provider_oauth_attempts WHERE cave_id=$1 AND connection_id=$2 AND state_hash=$3 AND status='pending' AND expires_at>now()",[cave,found.connection_id,tokenHash(state)])).rows[0];if(!a||a.actor_id!==actor||a.session_hash!==sessionHash)throw new AccessError(400,'oauth_invalid');const row=await this.row(db,cave,a.connection_id);if(row.status!=='oauth_pending'||row.authorization_version!==a.authorization_version)throw new AccessError(409,'connection_changed');await db.query("UPDATE provider_oauth_attempts SET status='consumed',consumed_at=now(),encrypted_flow=NULL WHERE cave_id=$1 AND connection_id=$2 AND id=$3",[cave,row.id,a.id]);return{...a,connection_version:row.version};},false);
  try{if(url.searchParams.has('error')){const code=url.searchParams.get('error');throw new ConnectorError(code==='admin_consent_required'||url.searchParams.get('error_codes')==='[90094]'?'admin_consent_required':code==='access_denied'?'consent_denied':'oauth_invalid');}const code=url.searchParams.get('code');if(!code||code.length>8192)throw new ConnectorError('oauth_invalid');const flow=this.required().cipher.open<Flow>(attempt.encrypted_flow,this.scope(attempt.cave_id,attempt.connection_id,'oauth:'+attempt.id)),discovery=await this.adapter(context,attempt.connection_id,attempt.authorization_version).complete(code,flow);
   return await this.admin(context,async(db,cave,actor)=>{const row=await this.row(db,cave,attempt.connection_id);if(row.status!=='oauth_pending'||row.authorization_version!==attempt.authorization_version)throw new AccessError(409,'connection_changed');if(row.provider_account_id&&(row.provider_account_id!==discovery.credentials.identity.accountId||row.provider_tenant_id!==discovery.credentials.identity.tenantId))throw new ConnectorError('identity_mismatch');const saved=await this.saveDiscovery(db,cave,row,discovery,false);await db.query("UPDATE provider_oauth_attempts SET status='succeeded' WHERE cave_id=$1 AND connection_id=$2 AND id=$3",[cave,row.id,attempt.id]);await this.event(db,cave,actor,saved,'oauth_completed');return{id:row.id};},false);
  }catch(error){await this.failure(context,attempt.connection_id,attempt.authorization_version,attempt.connection_version,errorCode(error),attempt.id);throw error;}
 }
 private async failure(context:CommandContext,id:string,authorizationVersion:number,expectedVersion:number,code:string,attemptId?:string){
  try{await this.admin(context,async(db,cave,actor)=>{const row=await this.row(db,cave,id);if(row.authorization_version!==authorizationVersion||row.version!==expectedVersion||row.status==='revoked')return;const status=code==='admin_consent_required'?'admin_consent_required':code==='consent_denied'?'consent_denied':['interaction_required','identity_mismatch','oauth_invalid'].includes(code)?'reconnect_required':'error';const updated=(await db.query('UPDATE provider_connections SET version=version+1,status=$3,last_error=$4,last_checked_at=now(),updated_at=now() WHERE cave_id=$1 AND id=$2 RETURNING *',[cave,id,status,code])).rows[0];if(attemptId)await db.query("UPDATE provider_oauth_attempts SET status='failed',encrypted_flow=NULL WHERE cave_id=$1 AND connection_id=$2 AND id=$3",[cave,id,attemptId]);await this.event(db,cave,actor,updated,'provider_failure');},false);}catch{/* An obsolete or unauthorized response cannot change current connection state. */}
 }
 private async saveDiscovery(db:PoolClient,cave:string,row:Row,discovery:MicrosoftDiscovery,changeAuthorization:boolean,selected?:{mailboxId:string|null;calendarId:string|null}){
  const d=discovery.credentials;if(row.provider_account_id&&(row.provider_account_id!==d.identity.accountId||row.provider_tenant_id!==d.identity.tenantId))throw new ConnectorError('identity_mismatch');const pick=(kind:string,id:string|null)=>id&&discovery.resources.some(r=>r.kind===kind&&r.id===id)?id:null;
  const mailbox=pick('mailbox',selected?selected.mailboxId:row.mailbox_id),calendar=pick('calendar',selected?selected.calendarId:row.calendar_id);if(selected&&(mailbox!==selected.mailboxId||calendar!==selected.calendarId))throw new AccessError(400,'resource_missing');
  await db.query('DELETE FROM provider_routing_claims WHERE cave_id=$1 AND connection_id=$2',[cave,row.id]);await db.query('DELETE FROM provider_credentials WHERE cave_id=$1 AND connection_id=$2',[cave,row.id]);await db.query('DELETE FROM provider_resources WHERE cave_id=$1 AND connection_id=$2',[cave,row.id]);
  for(const r of discovery.resources){if(r.ownerId!==d.identity.accountId)throw new ConnectorError('identity_mismatch');await db.query('INSERT INTO provider_resources(cave_id,connection_id,kind,id,name,owner_id,writable) VALUES($1,$2,$3,$4,$5,$6,false)',[cave,row.id,r.kind,r.id,r.name,r.ownerId]);}
  const nextAuth=row.authorization_version+(changeAuthorization?1:0),unchanged=mailbox===row.mailbox_id&&calendar===row.calendar_id,status=mailbox||calendar?row.status==='active'&&!changeAuthorization&&unchanged?'active':'unqualified':'selection_required';const updated=(await db.query('UPDATE provider_connections SET version=version+1,authorization_version=$3,status=$4,provider_tenant_id=$5,provider_account_id=$6,display_name=$7,username=$8,mailbox_id=$9,calendar_id=$10,expires_at=$11,last_checked_at=now(),last_success_at=now(),last_error=NULL,missing_resources=$12,updated_at=now() WHERE cave_id=$1 AND id=$2 RETURNING *',[cave,row.id,nextAuth,status,d.identity.tenantId,d.identity.accountId,d.identity.displayName,d.identity.username,mailbox,calendar,d.expiresAt,JSON.stringify(discovery.missing)])).rows[0];
  const encrypted=this.required().cipher.seal(d,this.scope(cave,row.id,'credentials:'+nextAuth));await db.query('INSERT INTO provider_credentials(cave_id,connection_id,authorization_version,ciphertext) VALUES($1,$2,$3,$4)',[cave,row.id,nextAuth,encrypted]);
  try{for(const [kind,id] of [['mailbox',mailbox],['calendar',calendar]])if(id)await db.query("INSERT INTO provider_routing_claims(cave_id,connection_id,provider,provider_tenant_id,provider_account_id,kind,resource_id) VALUES($1,$2,'microsoft365',$3,$4,$5,$6)",[cave,row.id,d.identity.tenantId,d.identity.accountId,kind,id]);}catch(error){if((error as any).code==='23505')throw new AccessError(409,'resource_already_routed');throw error;}return updated as Row;
 }
 async operate(context:CommandContext,id:unknown,kind:'select'|'inspect'|'activate'|'disconnect',input:unknown,key:unknown){
  if(!validId(key))throw new AccessError(400,'invalid_idempotency_key');const p=(kind==='select'?selectConnectionResourcesSchema:connectionVersionSchema).safeParse(input);if(!p.success)throw new AccessError(400,'invalid_connection');const hash=sha([kind,id,p.data]);
  const plan=await this.admin(context,async(db,cave,actor)=>{const row=await this.row(db,cave,id),old=await this.command(db,cave,actor,key,hash);if(old)return{replay:old};this.version(row,p.data.expectedVersion);
   if(kind==='disconnect'){await db.query('DELETE FROM provider_credentials WHERE cave_id=$1 AND connection_id=$2',[cave,row.id]);await db.query('DELETE FROM provider_routing_claims WHERE cave_id=$1 AND connection_id=$2',[cave,row.id]);await db.query("UPDATE provider_oauth_attempts SET status='cancelled',encrypted_flow=NULL WHERE cave_id=$1 AND connection_id=$2 AND status IN ('pending','consumed')",[cave,row.id]);const saved=(await db.query("UPDATE provider_connections SET version=version+1,authorization_version=authorization_version+1,status='revoked',last_error=NULL,updated_at=now() WHERE cave_id=$1 AND id=$2 RETURNING *",[cave,row.id])).rows[0];const result={id:row.id,version:saved.version};await this.journal(db,cave,actor,row.id,key,kind,hash,result);await this.event(db,cave,actor,saved,'disconnected');return{replay:result};}
   if(['revoked','oauth_pending'].includes(row.status))throw new AccessError(409,'connection_unavailable');const stored=(await db.query('SELECT ciphertext FROM provider_credentials WHERE cave_id=$1 AND connection_id=$2 AND authorization_version=$3',[cave,row.id,row.authorization_version])).rows[0];if(!stored)throw new AccessError(409,'reconnect_required');let credentials:MicrosoftCredentials;
   try{credentials=this.required().cipher.open<MicrosoftCredentials>(stored.ciphertext,this.scope(cave,row.id,'credentials:'+row.authorization_version));if(credentials.identity.accountId!==row.provider_account_id||credentials.identity.tenantId!==row.provider_tenant_id)throw new Error('Credential identity mismatch');}
   catch{await db.query('DELETE FROM provider_credentials WHERE cave_id=$1 AND connection_id=$2',[cave,row.id]);const invalid=(await db.query("UPDATE provider_connections SET version=version+1,authorization_version=authorization_version+1,status='reconnect_required',last_error='interaction_required',last_checked_at=now(),updated_at=now() WHERE cave_id=$1 AND id=$2 RETURNING *",[cave,row.id])).rows[0];await this.event(db,cave,actor,invalid,'credential_invalidated');return{credentialFailure:true};}
   if(kind==='activate'){if(!row.synthetic||!this.settings?.fixtureOrigin)throw new AccessError(409,'not_qualified');if(row.status!=='unqualified'||(!row.mailbox_id&&!row.calendar_id)||row.last_error||new Date(row.expires_at).getTime()<=Date.now())throw new AccessError(409,'connection_unavailable');const nextAuth=row.authorization_version+1;await db.query('DELETE FROM provider_credentials WHERE cave_id=$1 AND connection_id=$2',[cave,row.id]);const saved=(await db.query("UPDATE provider_connections SET version=version+1,authorization_version=$3,status='active',updated_at=now() WHERE cave_id=$1 AND id=$2 RETURNING *",[cave,row.id,nextAuth])).rows[0];await db.query('INSERT INTO provider_credentials(cave_id,connection_id,authorization_version,ciphertext) VALUES($1,$2,$3,$4)',[cave,row.id,nextAuth,this.required().cipher.seal(credentials,this.scope(cave,row.id,'credentials:'+nextAuth))]);const result={id:row.id,version:saved.version};await this.journal(db,cave,actor,row.id,key,kind,hash,result);await this.event(db,cave,actor,saved,'synthetic_activated');return{replay:result};}
   return{row,credentials};
  });if('replay'in plan)return plan.replay;if('credentialFailure'in plan)throw new AccessError(409,'reconnect_required');
  const row=plan.row!;let discovery:MicrosoftDiscovery;try{discovery=await this.adapter(context,row.id,row.authorization_version).inspect(plan.credentials!);}catch(error){await this.failure(context,row.id,row.authorization_version,row.version,errorCode(error));throw providerFailure(error);}
  return this.admin(context,async(db,cave,actor)=>{const current=await this.row(db,cave,row.id),old=await this.command(db,cave,actor,key,hash);if(old)return old;this.version(current,row.version);if(current.authorization_version!==row.authorization_version||current.status==='revoked')throw new AccessError(409,'connection_changed');const selection=kind==='select'?selectConnectionResourcesSchema.parse(input):undefined,saved=await this.saveDiscovery(db,cave,current,discovery,kind==='select',selection),result={id:row.id,version:saved.version};await this.journal(db,cave,actor,row.id,key,kind,hash,result);await this.event(db,cave,actor,saved,kind==='select'?'resources_selected':'health_checked');return result;});
 }
 // Entry point for future durable jobs: never accept a credential or a provider
 // account from the envelope. Each external request rechecks this authorization.
 async runDiscoveryJob(envelope:{caveId:string;connectionId:string;authorizationVersion:number}){
  const inspect=async()=>transaction(this.pool,async db=>{if(!validId(envelope.caveId)||!validId(envelope.connectionId))throw new AccessError(404,'connection_not_found');await lockCave(db,envelope.caveId);const row=await this.row(db,envelope.caveId,envelope.connectionId);if(row.status!=='active'||row.authorization_version!==envelope.authorizationVersion||!row.synthetic||!this.settings?.fixtureOrigin||new Date(row.expires_at).getTime()<=Date.now())throw new AccessError(409,'connection_unavailable');const value=(await db.query('SELECT ciphertext FROM provider_credentials WHERE cave_id=$1 AND connection_id=$2 AND authorization_version=$3',[envelope.caveId,row.id,row.authorization_version])).rows[0];if(!value)throw new AccessError(409,'connection_unavailable');return this.required().cipher.open<MicrosoftCredentials>(value.ciphertext,this.scope(envelope.caveId,row.id,'credentials:'+row.authorization_version));});
  const credentials=await inspect(),adapter=new MicrosoftAdapter(this.required().settings,this.appOrigin,this.environment,async()=>{await inspect();});const result=await adapter.inspect(credentials);await inspect();return{resources:result.resources,synthetic:true};
 }
}
