'use client';
import { useCallback,useEffect,useRef,useState,type FormEvent } from 'react';
type Cave={id:string;name:string;role:string};
type Session={identity:{id:string;name:string};activeCave:Cave|null;caves:Cave[];csrf:string};
type Resource={kind:'mailbox'|'calendar';id:string;name:string};
type Connection={id:string;label:string;version:number;status:string;synthetic:boolean;identity:{tenantId:string;accountId:string;displayName:string;username:string}|null;mailboxId:string|null;calendarId:string|null;resources:Resource[];capabilities:{operation:string;state:string;reason:string;evidence:string}[];expiresAt:string|null;lastCheckedAt:string|null;lastSuccessAt:string|null;lastSynchronizationAt:null;lastError:string|null;missingResources:string[];canActivate:boolean};
type List={caveId:string;configured:boolean;synthetic:boolean;items:Connection[]};
type Command={key:string;path:string;body:Record<string,unknown>;scope:string};
const states:Record<string,string>={oauth_pending:'Autorisation en attente',selection_required:'Ressources à choisir',unqualified:'Qualification requise',active:'Découverte active — simulation',consent_denied:'Consentement refusé',admin_consent_required:'Consentement administrateur requis',reconnect_required:'Reconnexion requise',error:'Connexion en erreur',revoked:'Déconnectée'};
const operations:Record<string,string>={discoverResources:'Découvrir les ressources',readMessages:'Lire les messages',syncMessages:'Synchroniser les messages',getBusyIntervals:'Lire les disponibilités',createCalendarEvent:'Créer un événement',findCalendarEvent:'Retrouver un événement',sendMessage:'Envoyer un message',reconcileMessage:'Vérifier un envoi',renewSubscription:'Renouveler les notifications'};
const errors:Record<string,string>={oauth_invalid:'Le retour Microsoft est invalide ou a expiré. Reconnectez la connexion concernée.',consent_denied:'Vous avez refusé le consentement. La connexion reste inactive.',admin_consent_required:'Microsoft exige le consentement d’un administrateur de votre organisation. Contactez-le puis reconnectez ce compte.',identity_mismatch:'Ce compte ne correspond pas à la connexion. Reconnectez le même compte ou créez une nouvelle connexion.',connection_changed:'La connexion a changé. Actualisez avant de recommencer.',cave_changed:'La cave active a changé. Actualisez votre espace.',role_forbidden:'Seul un administrateur de cette cave peut modifier les connexions.',session_required:'Votre session a expiré. Reconnectez-vous.',access_revoked:'Votre accès à cette cave a été révoqué.',resource_missing:'Choisissez une ressource autorisée dans la liste. Vos choix sont conservés.',resource_already_routed:'Cette ressource est déjà reliée à une connexion. Déconnectez son ancien rattachement avant de la choisir ici.',rate_limited:'Microsoft limite les requêtes. Patientez avant de vérifier à nouveau.',interaction_required:'L’autorisation doit être renouvelée. Utilisez Reconnecter.',permission_missing:'Un droit Microsoft nécessaire manque. Reconnectez pour vérifier les autorisations.',not_qualified:'Cette connexion réelle doit être qualifiée avant toute activation.',microsoft_not_configured:'Microsoft n’est pas configuré pour cet environnement.',provider_unavailable:'Microsoft est momentanément indisponible.',reconnect_required:'Actualisez puis reconnectez ce compte pour vérifier de nouveau ses ressources.',connection_unavailable:'Cette connexion ne permet pas encore cette action.',oauth_expired:'Cette autorisation a expiré. Reconnectez la connexion concernée.'};
const time=(v:string|null)=>v?new Intl.DateTimeFormat('fr-CH',{dateStyle:'medium',timeStyle:'short',timeZone:'Europe/Zurich'}).format(new Date(v)):'Aucun contrôle';
const scope=(s:Session)=>`encave.connections.${s.identity.id}.${s.activeCave?.id}`;
const readPending=(s:Session):Command|null=>{try{const p=JSON.parse(sessionStorage.getItem(scope(s))??'null');return p&&p.scope===scope(s)&&typeof p.key==='string'&&typeof p.path==='string'&&p.path.startsWith('/api/connections/')&&p.body?p:null;}catch{return null;}};

export default function Connections(){
 const [session,setSession]=useState<Session|null>(null),[list,setList]=useState<List|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState(''),[label,setLabel]=useState(''),[pending,setPending]=useState<Command|null>(null),[confirm,setConfirm]=useState<Connection|null>(null);
 const generation=useRef(0),current=useRef<Session|null>(null),lock=useRef(false),channel=useRef<BroadcastChannel|null>(null),dialog=useRef<HTMLDialogElement>(null),opener=useRef<HTMLElement|null>(null),summary=useRef<HTMLDivElement|null>(null);
 const load=useCallback(async()=>{const g=++generation.current;setLoading(true);setList(null);setConfirm(null);
  try{const r=await fetch('/api/session',{cache:'no-store'});if(!r.ok)throw new Error('session_required');const s:Session=await r.json();if(g!==generation.current)return;const changed=current.current&&scope(current.current)!==scope(s);if(changed){setError('');setStatus('');setLabel('');}current.current=s;setSession(s);const saved=readPending(s);setPending(saved);if(saved?.path==='/api/connections/microsoft/start'&&saved.body.connectionId===null&&typeof saved.body.label==='string')setLabel(saved.body.label);if(!s.activeCave)return;
   const response=await fetch('/api/connections',{cache:'no-store',headers:{'x-encave-cave':s.activeCave.id}}),data=await response.json();if(g!==generation.current)return;if(!response.ok)throw new Error(data.error);if(data.caveId!==s.activeCave.id)throw new Error('cave_changed');setList(data);
  }catch(e){if(g===generation.current){setError(errors[(e as Error).message]??'Votre espace est indisponible. Actualisez pour réessayer.');if((e as Error).message==='session_required'){setSession(null);current.current=null;setPending(null);}}}finally{if(g===generation.current)setLoading(false);}
 },[]);
 useEffect(()=>{void load();const query=new URLSearchParams(location.search);if(query.has('error'))setError(errors[query.get('error')!]??errors['oauth_invalid']!);else if(query.get('result')==='connected')setStatus('Compte autorisé. Choisissez ses ressources puis vérifiez son état.');if(query.has('error')||query.has('result'))history.replaceState(null,'','/connexions');
  const c=new BroadcastChannel('encave-context');channel.current=c;c.onmessage=()=>void load();const visible=()=>{if(document.visibilityState==='visible')void load();};document.addEventListener('visibilitychange',visible);return()=>{generation.current++;c.close();document.removeEventListener('visibilitychange',visible);};
 },[load]);
 useEffect(()=>{if(confirm){dialog.current?.showModal();}else if(dialog.current?.open){dialog.current.close();opener.current?.focus();}},[confirm]);
 const failure=(message:string)=>{setError(message);requestAnimationFrame(()=>summary.current?.focus());};
 async function execute(path:string,body:Record<string,unknown>,retry?:Command){
  const s=current.current;if(lock.current||!s?.activeCave)return;if(pending&&!retry)return;const g=generation.current,command=retry??{key:crypto.randomUUID(),path,body,scope:scope(s)};if(command.scope!==scope(s))return;
  try{sessionStorage.setItem(scope(s),JSON.stringify(command));}catch{failure('Le navigateur ne peut pas conserver la commande. Autorisez le stockage de session avant de réessayer.');return;}
  lock.current=true;setBusy(true);setPending(command);setError('');setStatus('Action en cours…');setConfirm(null);
  try{const r=await fetch(command.path,{method:'POST',headers:{'content-type':'application/json','x-csrf-token':s.csrf,'x-encave-cave':s.activeCave.id,'idempotency-key':command.key},body:JSON.stringify(command.body)}),result=await r.json();if(g!==generation.current)return;
   if(!r.ok){if(r.status<500&&(!retry||(r.status===409&&result.error==='connection_changed'))){sessionStorage.removeItem(scope(s));setPending(null);}throw new Error(result.error);}
   sessionStorage.removeItem(scope(s));setPending(null);setStatus(result.requiresReconnect?'La connexion existe déjà. Reconnectez-la pour renouveler l’autorisation.':result.alreadyCompleted?'La connexion a été retrouvée.':'Modification enregistrée.');if(result.url){location.assign(result.url);return;}await load();
  }catch(e){if(g===generation.current){const saved=readPending(s);setPending(saved);setStatus('');failure(saved?'Le résultat n’est pas confirmé. Vérifiez la même commande avant toute autre modification.':errors[(e as Error).message]??'L’action a échoué. Vos choix sont conservés.');}}
  finally{lock.current=false;setBusy(false);}
 }
 const start=(row?:Connection)=>void execute('/api/connections/microsoft/start',{provider:'microsoft365',connectionId:row?.id??null,expectedVersion:row?.version??0,label:row?.label??label.trim()});
 const action=(row:Connection,kind:string,extra:Record<string,unknown>={})=>void execute('/api/connections/'+row.id+'/'+kind,{expectedVersion:row.version,...extra});
 async function switchCave(id:string){const s=current.current;if(!s||busy||pending)return;setBusy(true);const g=generation.current;try{const r=await fetch('/api/caves/switch',{method:'POST',headers:{'content-type':'application/json','x-csrf-token':s.csrf,'x-encave-cave':s.activeCave?.id??''},body:JSON.stringify({caveId:id})});if(g!==generation.current)return;if(!r.ok)throw new Error();channel.current?.postMessage('cave_changed');await load();}catch{failure('Le changement de cave a échoué. Actualisez pour vérifier.');}finally{setBusy(false);}}
 const disabled=busy||Boolean(pending)||loading,admin=session?.activeCave?.role==='admin';
 return <div className="workspace-shell connection-shell"><aside className="workspace-nav"><a className="brand" href="/demandes">EnCave<span>Assistant</span></a><nav aria-label="Navigation principale"><a href="/demandes">Demandes</a><a href="/connexions" aria-current="page">Connexions</a><a href="/espace">Paramètres</a></nav></aside><div className="workspace-content"><header className="workspace-header"><div><span className="eyebrow">ESPACE CAVE</span><strong>{session?.activeCave?.name??'Votre espace'}</strong>{session&&session.caves.length>1&&<label className="cave-picker">Cave active<select value={session.activeCave?.id??''} disabled={disabled} onChange={e=>void switchCave(e.target.value)}>{session.caves.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}</div><span>{session?.identity.name}</span></header><main id="contenu" className="workspace-main connections-main"><p className="eyebrow">COMPTES ET RESSOURCES</p><h1>Connexions</h1><p>Reliez les comptes de votre cave, choisissez leurs ressources et suivez les autorisations.</p>
 {error&&<div className="alert error" role="alert" tabIndex={-1} ref={summary}>{error}</div>}<p role="status" aria-live="polite">{status}</p>
 {pending&&<section className="panel"><h2>Commande à vérifier</h2><p>La vérification reprend la commande enregistrée pour cette cave.</p><button className="button primary" disabled={busy||loading} onClick={()=>void execute(pending.path,pending.body,pending)}>Vérifier la commande</button></section>}
 <div className="form-actions"><button className="button secondary" disabled={busy} onClick={()=>void load()}>Actualiser</button>{!session&&!loading&&<a className="button primary" href="/connexion">Se reconnecter</a>}</div>
 {loading&&<p className="loading-state">Chargement des connexions…</p>}
 {!loading&&session&&!session.activeCave&&<section className="panel"><h2>Aucune cave accessible</h2><p>Un administrateur doit vous donner accès à une cave.</p></section>}
 {list&&!list.configured&&<section className="panel"><h2>Microsoft non configuré</h2><p>L’environnement ne dispose pas encore d’une inscription Microsoft autorisée. Les demandes manuelles restent disponibles.</p><a className="button primary" href="/demandes?nouvelle=1">Saisir une demande</a></section>}
 {list?.synthetic&&<p className="connection-notice">Environnement de test : comptes et réponses Microsoft synthétiques. Aucun accès à un compte réel.</p>}
 {list?.configured&&admin&&<section className="panel"><h2>Ajouter un compte Microsoft 365</h2><p>Compte professionnel ou scolaire, boîte personnelle et calendrier principal. Les comptes partagés demandent une qualification distincte.</p><form onSubmit={(e:FormEvent)=>{e.preventDefault();start();}}><label htmlFor="connection-label">Nom de la connexion</label><input id="connection-label" required maxLength={160} value={label} disabled={disabled} onChange={e=>setLabel(e.target.value)} placeholder="Ex. Accueil de la cave"/><p className="muted">Le consentement demandé permet de découvrir votre boîte et votre calendrier. L’envoi de messages et l’écriture calendrier ne sont pas encore pris en charge.</p><button className="button primary" disabled={disabled||!label.trim()}>Connecter Microsoft 365</button></form></section>}
 {list&&!admin&&<p className="connection-notice">Consultation seule. Un administrateur de cette cave peut gérer ses connexions.</p>}
 {list&&list.items.length===0&&list.configured&&<section className="panel empty-state"><h2>Aucune connexion</h2><p>Ajoutez un compte pour découvrir ses ressources. Votre travail interne reste disponible.</p></section>}
 {list?.items.map(row=><ConnectionCard key={row.id+':'+row.version} row={row} admin={Boolean(admin)} configured={list.configured} pending={pending} disabled={disabled} action={action} start={start} disconnect={()=>{opener.current=document.activeElement as HTMLElement;setConfirm(row);}}/>)}
 <dialog ref={dialog} className="confirm-dialog" aria-labelledby="disconnect-heading" onCancel={e=>{e.preventDefault();setConfirm(null);}}><h2 id="disconnect-heading">Déconnecter ce compte ?</h2><p><strong>{confirm?.label}</strong> · {session?.activeCave?.name}</p><p>Les nouvelles opérations de cette connexion seront bloquées et ses jetons supprimés côté EnCave. Les dossiers et les autres connexions sont conservés.</p><p>Cette action ne retire pas le consentement dans Microsoft et n’annule pas une opération déjà reçue par Microsoft.</p><div className="dialog-actions"><button autoFocus className="button secondary" onClick={()=>setConfirm(null)}>Annuler</button><button className="button danger" disabled={busy} onClick={()=>confirm&&action(confirm,'disconnect')}>Déconnecter ce compte</button></div></dialog>
 </main></div></div>;
}
function ConnectionCard({row,admin,configured,pending,disabled,action,start,disconnect}:{row:Connection;admin:boolean;configured:boolean;pending:Command|null;disabled:boolean;action:(r:Connection,k:string,e?:Record<string,unknown>)=>void;start:(r:Connection)=>void;disconnect:()=>void}){
 const saved=pending?.path==='/api/connections/'+row.id+'/resources'?pending.body:null;
 const [mailbox,setMailbox]=useState(saved?typeof saved.mailboxId==='string'?saved.mailboxId:'':row.mailboxId??''),[calendar,setCalendar]=useState(saved?typeof saved.calendarId==='string'?saved.calendarId:'':row.calendarId??''),[invalid,setInvalid]=useState(false);
 const selectable=configured&&row.identity&&!['oauth_pending','revoked','consent_denied','admin_consent_required'].includes(row.status),canInspect=selectable;
 return <section className="panel connection-card" aria-labelledby={'connection-'+row.id}><div className="section-heading"><div><p className="eyebrow">MICROSOFT 365{row.synthetic?' · SIMULATION':''}</p><h2 id={'connection-'+row.id}>{row.label}</h2></div><span className="inquiry-badge">{states[row.status]??'À vérifier'}</span></div>
 {row.identity?<><p><strong>{row.identity.displayName}</strong><br/>{row.identity.username}</p><dl className="facts"><dt>Organisation</dt><dd>{row.identity.tenantId}</dd><dt>Compte vérifié</dt><dd>{row.identity.accountId}</dd></dl></>:<p>Aucun compte Microsoft vérifié.</p>}
 {row.lastError&&<p className="alert error">{errors[row.lastError]??'Le dernier contrôle a échoué. Reconnectez pour vérifier.'}</p>}
 <ol className="connection-steps" aria-label="Étapes de connexion"><li>1. Autoriser le compte</li><li>2. Choisir les ressources</li><li>3. Qualifier les capacités</li></ol>
 {row.missingResources.length>0&&<p>Ressources indisponibles : {row.missingResources.map(k=>k==='mailbox'?'boîte':'calendrier').join(', ')}. Vérifiez les droits auprès de votre organisation.</p>}
 {selectable&&admin&&<form onSubmit={e=>{e.preventDefault();if(!mailbox&&!calendar){setInvalid(true);document.getElementById('mailbox-'+row.id)?.focus();return;}setInvalid(false);action(row,'resources',{mailboxId:mailbox||null,calendarId:calendar||null});}}><div className="form-grid"><label>Boîte autorisée<select id={'mailbox-'+row.id} disabled={disabled} value={mailbox} aria-invalid={invalid} aria-describedby={invalid?'selection-error-'+row.id:undefined} onChange={e=>setMailbox(e.target.value)}><option value="">Ne pas utiliser de boîte</option>{row.resources.filter(r=>r.kind==='mailbox').map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>Calendrier autorisé<select disabled={disabled} value={calendar} aria-invalid={invalid} aria-describedby={invalid?'selection-error-'+row.id:undefined} onChange={e=>setCalendar(e.target.value)}><option value="">Ne pas utiliser de calendrier</option>{row.resources.filter(r=>r.kind==='calendar').map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label></div>{invalid&&<p className="field-error" id={'selection-error-'+row.id} role="alert">Choisissez au moins une ressource autorisée.</p>}<button className="button primary" disabled={disabled}>Enregistrer les ressources</button></form>}
 {(!admin||!configured)&&<dl className="facts"><dt>Boîte choisie</dt><dd>{row.resources.find(r=>r.id===row.mailboxId)?.name??'Aucune'}</dd><dt>Calendrier choisi</dt><dd>{row.resources.find(r=>r.id===row.calendarId)?.name??'Aucun'}</dd></dl>}
 <dl className="facts connection-health"><dt>Dernier contrôle</dt><dd>{time(row.lastCheckedAt)}</dd><dt>Dernier succès</dt><dd>{time(row.lastSuccessAt)}</dd><dt>Échéance du jeton</dt><dd>{row.expiresAt?time(row.expiresAt):'Inconnue'}</dd><dt>Synchronisation</dt><dd>Non effectuée</dd></dl>
 <h3>Capacités</h3><ul className="capability-list">{row.capabilities.map(c=><li key={c.operation}><span>{operations[c.operation]??c.operation}</span><strong>{c.state==='available'?'Disponible en simulation':c.reason==='not_supported'?'Non prise en charge':c.reason==='resource_missing'?'Ressource indisponible':'Non qualifiée'}</strong></li>)}</ul>
 {row.status==='unqualified'&&<p>{row.synthetic?'La découverte peut être activée pour ce simulateur uniquement.':'Une qualification technique sur un environnement autorisé est nécessaire avant toute activation.'}</p>}
 {admin&&<div className="form-actions">{canInspect&&<button className="button secondary" disabled={disabled} onClick={()=>action(row,'inspect')}>Vérifier la connexion</button>}{row.canActivate&&<button className="button primary" disabled={disabled} onClick={()=>action(row,'activate')}>Activer la découverte simulée</button>}<button className="button secondary" disabled={disabled||!configured} onClick={()=>start(row)}>Reconnecter</button>{row.status!=='revoked'&&<button className="button danger" disabled={disabled} onClick={disconnect}>Déconnecter</button>}</div>}
 </section>;
}
